# Appendix: Build a model of your own system

## Background Readings:

* This primer: at least chapters 1-3; chapters 5-6, 8-9 are also useful.
* Soetaert and Hermann 2009. All of it is useful, but especially the chapters used in this primer.

## Steps

1. **Identify the scope** and focus of your model, including,
   a. state variables (with units),
   a. spatial boundaries, 
   a. time scale, or temporal boundaries,
   a. inputs and outputs for the system, 
   a. fluxes between state variables,
   a. the state variables *upon which the fluxes depend* (e.g., litterfall from trees to soils depends directly on only trees but not soils); this gives you the **order** of the rate equations.
1. Create a **budget**, including,   
   a. amount *in* each state variable,
   a. *annual fluxes between* state variables; if you can't find these in the literature, figure out ways to get very rough approximate estimates.
1. Write out a model:
   a. **for each flux**, write an *explicit mathematical function for each process* in that flux (see, e.g., the NPZD model). (You will estimate rate paramters later.)
   a. **for each state variable**, write an *explicit rate equation* using the functions for the fluxes in the previous step.
   a. **estimate each parameter** in one of these ways: 
      i. use algebra to calculate instantaneous rates from *annual fluxes* and the magnitude of the state variables upon which the fluxes depend, or
      i. if there is an estimate in relevant literature for your particular rate parameter, use that, or
      i. use both approaches and try them both out.
1. **Code the model in R**, including,
   a. writing an ODE function, a vector of parameters; start with three or four years only.
   a. run and then troubleshoot the model.
1. Perform sensitivity analysis (chap. 6).
1. Consider including data from an external source (chap. 9)
1. Consider letting R try to fit rate parameters through optimization (chap. 8).
1. Present your findings in a simple written form and short oral presentation.



