--- 
title: "A Primer of Ecosystem Modeling - a work in progress"
author: "Hank Stevens, BIO 672"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output:
    bookdown::gitbook
documentclass: book
bibliography: [/Users/stevenmh/myLibrary.bib, book.bib, packages.bib]
biblio-style: plain
link-citations: yes
description: "This provides a part of a foundation in understanding ecosystem models."
github-repo: HankStevens/ecosystems-primer
output_dir: "docs"
clean: FALSE
---

# Prerequisites

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='markup', 
                      warning=FALSE, message=FALSE, 
                      fig.path = "/Users/stevenmh/Projects/ecosystems-primer/figs/",
                      knitr.graphics.auto_pdf = TRUE,
                      message=FALSE, out.width="75%")
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')

library(deSolve)
library(tidyverse)
library(kableExtra) #kbl
library(DiagrammeR) # grViz
library(DiagrammeRsvg)
library(bbmle) # MLE with mle2() 
```

For this R primer, you'll need to read several chapters of @soetaert2009 which are available on the Canvas website. Their book is an excellent source for those interested in ecosystem modeling, especially in aquatic systems. We will use bits of it along with this online text to get a little more comfortable with ecosystem processes and models. 

I also assume that you are reading a book on ecosystem ecology such as @chapin2011.

## Must do's

Read background material as needed.

* Install or update R (4.0.3, as of Jan 2021)
* Install or update RStudio
* Install select R packages: 'deSolve', 'tidyverse', 'LakeMetabolizer`, 'lubridate'

Also, before doing most tasks in this primer, load deSolve and tidyverse with `library(deSolve); library(tidyverse)`.

The R **working directory** is the place R automatically looks for files. For simplicity, I will refer to the R **working directory** as `Rwork`. Therefore, `Rwork/data` would be a folder or directory called `data` inside `Rwork`. At any point in time, you can find out what your working directory is using `getwd()`. You can set your working directory using `setwd("HD/MyStuff/Rwork")`, where "HD/MyStuff/Rwork" is the path to what you want your working directory to be. You can also use the "Session" pull-down menu in RStudio.

## A couple of useful citations

@Carey2018PLoS. Ten simple rules for biologists learning to program. PLoS Computional Biology 14(1): e1005871. https://doi.org/10.1371/journal.pcbi.1005871

@Bodner2021PLoS. Ten simple rules for tackling your first mathematical models: A guide for graduate students by graduate students. PLOS Computational Biology 17(1): e1008539.  https://doi.org/10.1371/journal.pcbi.1008539

