<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Describing a nitrogen budget | A Primer of Ecosystem Modeling - a work in progress</title>
  <meta name="description" content="This provides a part of a foundation in understanding ecosystem models." />
  <meta name="generator" content="bookdown 0.45 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Describing a nitrogen budget | A Primer of Ecosystem Modeling - a work in progress" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This provides a part of a foundation in understanding ecosystem models." />
  <meta name="github-repo" content="HankStevens/ecosystems-primer" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Describing a nitrogen budget | A Primer of Ecosystem Modeling - a work in progress" />
  
  <meta name="twitter:description" content="This provides a part of a foundation in understanding ecosystem models." />
  

<meta name="author" content="Hank Stevens, BIO 672" />


<meta name="date" content="2026-02-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>
<link rel="next" href="lake-metabolism.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prerequisites</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#must-dos"><i class="fa fa-check"></i><b>1.1</b> Must do’s</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#a-couple-of-useful-citations"><i class="fa fa-check"></i><b>1.2</b> A couple of useful citations</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#a-final-suggestion"><i class="fa fa-check"></i><b>1.3</b> A final suggestion</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="simple-budgets.html"><a href="simple-budgets.html"><i class="fa fa-check"></i><b>2</b> Simple Budgets</a>
<ul>
<li class="chapter" data-level="2.1" data-path="simple-budgets.html"><a href="simple-budgets.html#learning-objectives"><i class="fa fa-check"></i><b>2.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="2.2" data-path="simple-budgets.html"><a href="simple-budgets.html#one-compartment-models"><i class="fa fa-check"></i><b>2.2</b> One-compartment models</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="simple-budgets.html"><a href="simple-budgets.html#example-1-lake-phosphorus"><i class="fa fa-check"></i><b>2.2.1</b> Example 1: Lake Phosphorus</a></li>
<li class="chapter" data-level="2.2.2" data-path="simple-budgets.html"><a href="simple-budgets.html#example-2-forest-floor-leaf-litter"><i class="fa fa-check"></i><b>2.2.2</b> Example 2: Forest Floor Leaf Litter</a></li>
<li class="chapter" data-level="2.2.3" data-path="simple-budgets.html"><a href="simple-budgets.html#example-3-pond-water-budget"><i class="fa fa-check"></i><b>2.2.3</b> Example 3: Pond Water Budget</a></li>
<li class="chapter" data-level="2.2.4" data-path="simple-budgets.html"><a href="simple-budgets.html#example-4-soil-nitrogen-pool"><i class="fa fa-check"></i><b>2.2.4</b> Example 4: Soil Nitrogen Pool</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="simple-budgets.html"><a href="simple-budgets.html#more-complex-one-compartment-models"><i class="fa fa-check"></i><b>2.3</b> More complex one-compartment models</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="simple-budgets.html"><a href="simple-budgets.html#example-5-estuary-nitrogen-cycling"><i class="fa fa-check"></i><b>2.3.1</b> Example 5: Estuary Nitrogen Cycling</a></li>
<li class="chapter" data-level="2.3.2" data-path="simple-budgets.html"><a href="simple-budgets.html#example-6-tropical-forest-carbon-balance"><i class="fa fa-check"></i><b>2.3.2</b> Example 6: Tropical Forest Carbon Balance</a></li>
<li class="chapter" data-level="2.3.3" data-path="simple-budgets.html"><a href="simple-budgets.html#example-7-urban-stormwater-detention-basin"><i class="fa fa-check"></i><b>2.3.3</b> Example 7: Urban Stormwater Detention Basin</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="simple-budgets.html"><a href="simple-budgets.html#two-compartment-models"><i class="fa fa-check"></i><b>2.4</b> Two-compartment models</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="simple-budgets.html"><a href="simple-budgets.html#general-template-for-two-compartment-models"><i class="fa fa-check"></i><b>2.4.1</b> General Template for Two-Compartment Models</a></li>
<li class="chapter" data-level="2.4.2" data-path="simple-budgets.html"><a href="simple-budgets.html#example-8-soil-groundwater-nitrogen-system"><i class="fa fa-check"></i><b>2.4.2</b> Example 8: Soil-Groundwater Nitrogen System</a></li>
<li class="chapter" data-level="2.4.3" data-path="simple-budgets.html"><a href="simple-budgets.html#example-9-vegetation-litter-carbon-system"><i class="fa fa-check"></i><b>2.4.3</b> Example 9: Vegetation-Litter Carbon System</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="simple-budgets.html"><a href="simple-budgets.html#answers"><i class="fa fa-check"></i><b>2.5</b> Answers</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="first-order-compartments.html"><a href="first-order-compartments.html"><i class="fa fa-check"></i><b>3</b> Simple Mass-specific Rates</a>
<ul>
<li class="chapter" data-level="3.1" data-path="first-order-compartments.html"><a href="first-order-compartments.html#learning-objectives-1"><i class="fa fa-check"></i><b>3.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="3.2" data-path="first-order-compartments.html"><a href="first-order-compartments.html#key-concepts"><i class="fa fa-check"></i><b>3.2</b> Key Concepts</a></li>
<li class="chapter" data-level="3.3" data-path="first-order-compartments.html"><a href="first-order-compartments.html#solving-rate-equations"><i class="fa fa-check"></i><b>3.3</b> Solving rate equations</a></li>
<li class="chapter" data-level="3.4" data-path="first-order-compartments.html"><a href="first-order-compartments.html#one-compartment-models-1"><i class="fa fa-check"></i><b>3.4</b> One-compartment models</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="first-order-compartments.html"><a href="first-order-compartments.html#worked-example-lake-phosphorus-with-flushing"><i class="fa fa-check"></i><b>3.4.1</b> Worked Example: Lake phosphorus with flushing</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="first-order-compartments.html"><a href="first-order-compartments.html#problems"><i class="fa fa-check"></i><b>3.5</b> Problems</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="first-order-compartments.html"><a href="first-order-compartments.html#example-1-watershed-nitrogen-loss"><i class="fa fa-check"></i><b>3.5.1</b> Example 1: Watershed Nitrogen Loss</a></li>
<li class="chapter" data-level="3.5.2" data-path="first-order-compartments.html"><a href="first-order-compartments.html#example-2-soil-organic-matter-decomposition"><i class="fa fa-check"></i><b>3.5.2</b> Example 2: Soil Organic Matter Decomposition</a></li>
<li class="chapter" data-level="3.5.3" data-path="first-order-compartments.html"><a href="first-order-compartments.html#example-3-forest-canopy-nitrogen-with-multiple-losses"><i class="fa fa-check"></i><b>3.5.3</b> Example 3: Forest Canopy Nitrogen with Multiple Losses</a></li>
<li class="chapter" data-level="3.5.4" data-path="first-order-compartments.html"><a href="first-order-compartments.html#example-4-stream-dissolved-organic-carbon"><i class="fa fa-check"></i><b>3.5.4</b> Example 4: Stream Dissolved Organic Carbon</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="first-order-compartments.html"><a href="first-order-compartments.html#two-compartment-models-1"><i class="fa fa-check"></i><b>3.6</b> Two-compartment models</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="first-order-compartments.html"><a href="first-order-compartments.html#key-concepts-for-coupled-compartments"><i class="fa fa-check"></i><b>3.6.1</b> Key concepts for coupled compartments</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="first-order-compartments.html"><a href="first-order-compartments.html#answer-key"><i class="fa fa-check"></i><b>3.7</b> Answer Key</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>4</b> Introduction to ecosystem models</a>
<ul>
<li class="chapter" data-level="4.1" data-path="intro.html"><a href="intro.html#why-models"><i class="fa fa-check"></i><b>4.1</b> Why models?</a></li>
<li class="chapter" data-level="4.2" data-path="intro.html"><a href="intro.html#whats-an-ecosystem"><i class="fa fa-check"></i><b>4.2</b> What’s an ecosystem?</a></li>
<li class="chapter" data-level="4.3" data-path="intro.html"><a href="intro.html#whats-an-ecosystem-model"><i class="fa fa-check"></i><b>4.3</b> What’s an ecosystem model?</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="intro.html"><a href="intro.html#units-of-terms"><i class="fa fa-check"></i><b>4.3.1</b> Units of terms</a></li>
<li class="chapter" data-level="4.3.2" data-path="intro.html"><a href="intro.html#other-ideas"><i class="fa fa-check"></i><b>4.3.2</b> Other ideas</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="intro.html"><a href="intro.html#steps-in-modeling"><i class="fa fa-check"></i><b>4.4</b> Steps in modeling</a></li>
<li class="chapter" data-level="4.5" data-path="intro.html"><a href="intro.html#an-example-in-r"><i class="fa fa-check"></i><b>4.5</b> An example in R</a></li>
<li class="chapter" data-level="4.6" data-path="intro.html"><a href="intro.html#analytical-solutions-to-rate-equations"><i class="fa fa-check"></i><b>4.6</b> Analytical solutions to rate equations</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="N.html"><a href="N.html"><i class="fa fa-check"></i><b>5</b> Describing a nitrogen budget</a>
<ul>
<li class="chapter" data-level="5.1" data-path="N.html"><a href="N.html#learning-objectives-2"><i class="fa fa-check"></i><b>5.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="5.2" data-path="N.html"><a href="N.html#background-readings"><i class="fa fa-check"></i><b>5.2</b> Background Readings</a></li>
<li class="chapter" data-level="5.3" data-path="N.html"><a href="N.html#understanding-the-hubbard-brook-system"><i class="fa fa-check"></i><b>5.3</b> Understanding the Hubbard Brook System</a></li>
<li class="chapter" data-level="5.4" data-path="N.html"><a href="N.html#getting-started"><i class="fa fa-check"></i><b>5.4</b> Getting started</a></li>
<li class="chapter" data-level="5.5" data-path="N.html"><a href="N.html#classifying-the-fluxes"><i class="fa fa-check"></i><b>5.5</b> Classifying the Fluxes</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="N.html"><a href="N.html#quick-check-1"><i class="fa fa-check"></i><b>5.5.1</b> Quick Check 1</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="N.html"><a href="N.html#write-balance-equations"><i class="fa fa-check"></i><b>5.6</b> Write Balance Equations</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="N.html"><a href="N.html#quick-check-2"><i class="fa fa-check"></i><b>5.6.1</b> Quick Check 2</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="N.html"><a href="N.html#assess-the-total-system-budget"><i class="fa fa-check"></i><b>5.7</b> Assess the Total System Budget</a></li>
<li class="chapter" data-level="5.8" data-path="N.html"><a href="N.html#mathematical-forms-for-fluxes"><i class="fa fa-check"></i><b>5.8</b> Mathematical Forms for Fluxes</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="N.html"><a href="N.html#complete-balance-equations"><i class="fa fa-check"></i><b>5.8.1</b> Complete Balance Equations</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="N.html"><a href="N.html#a-critical-detail-consistent-sign-conventions"><i class="fa fa-check"></i><b>5.9</b> A Critical Detail: Consistent Sign Conventions</a></li>
<li class="chapter" data-level="5.10" data-path="N.html"><a href="N.html#parameterization"><i class="fa fa-check"></i><b>5.10</b> Parameterization</a>
<ul>
<li class="chapter" data-level="5.10.1" data-path="N.html"><a href="N.html#the-challenge-annual-rates-vs.-instantaneous-rates"><i class="fa fa-check"></i><b>5.10.1</b> The Challenge: Annual Rates vs. Instantaneous Rates</a></li>
<li class="chapter" data-level="5.10.2" data-path="N.html"><a href="N.html#approach-1-annual-incremental-rates-simpler"><i class="fa fa-check"></i><b>5.10.2</b> Approach 1: Annual Incremental Rates (Simpler)</a></li>
<li class="chapter" data-level="5.10.3" data-path="N.html"><a href="N.html#approach-2-instantaneous-rates-using-logarithms-more-accurate"><i class="fa fa-check"></i><b>5.10.3</b> Approach 2: Instantaneous Rates Using Logarithms (More Accurate)</a></li>
<li class="chapter" data-level="5.10.4" data-path="N.html"><a href="N.html#quick-check-3"><i class="fa fa-check"></i><b>5.10.4</b> Quick Check 3</a></li>
</ul></li>
<li class="chapter" data-level="5.11" data-path="N.html"><a href="N.html#calculating-all-parameters-in-r"><i class="fa fa-check"></i><b>5.11</b> Calculating All Parameters in R</a>
<ul>
<li class="chapter" data-level="5.11.1" data-path="N.html"><a href="N.html#parameter-table-with-biological-interpretation"><i class="fa fa-check"></i><b>5.11.1</b> Parameter Table with Biological Interpretation</a></li>
</ul></li>
<li class="chapter" data-level="5.12" data-path="N.html"><a href="N.html#mathematical-solution"><i class="fa fa-check"></i><b>5.12</b> Mathematical Solution</a></li>
<li class="chapter" data-level="5.13" data-path="N.html"><a href="N.html#interpreting-the-results"><i class="fa fa-check"></i><b>5.13</b> Interpreting the Results</a>
<ul>
<li class="chapter" data-level="5.13.1" data-path="N.html"><a href="N.html#the-key-problem"><i class="fa fa-check"></i><b>5.13.1</b> The Key Problem</a></li>
<li class="chapter" data-level="5.13.2" data-path="N.html"><a href="N.html#mass-balance-check"><i class="fa fa-check"></i><b>5.13.2</b> Mass Balance Check</a></li>
</ul></li>
<li class="chapter" data-level="5.14" data-path="N.html"><a href="N.html#exercise-add-self-limitation"><i class="fa fa-check"></i><b>5.14</b> Exercise: Add Self-Limitation</a>
<ul>
<li class="chapter" data-level="5.14.1" data-path="N.html"><a href="N.html#your-task"><i class="fa fa-check"></i><b>5.14.1</b> Your Task</a></li>
<li class="chapter" data-level="5.14.2" data-path="N.html"><a href="N.html#work-on-this-before-looking-at-the-solution"><i class="fa fa-check"></i><b>5.14.2</b> Work on This Before Looking at the Solution!</a></li>
<li class="chapter" data-level="5.14.3" data-path="N.html"><a href="N.html#solution-self-limited-model"><i class="fa fa-check"></i><b>5.14.3</b> Solution: Self-Limited Model</a></li>
<li class="chapter" data-level="5.14.4" data-path="N.html"><a href="N.html#questions-to-ponder"><i class="fa fa-check"></i><b>5.14.4</b> Questions to Ponder</a></li>
</ul></li>
<li class="chapter" data-level="5.15" data-path="N.html"><a href="N.html#saving-your-model-function"><i class="fa fa-check"></i><b>5.15</b> Saving Your Model Function</a></li>
<li class="chapter" data-level="5.16" data-path="N.html"><a href="N.html#common-issues-and-troubleshooting"><i class="fa fa-check"></i><b>5.16</b> Common Issues and Troubleshooting</a>
<ul>
<li class="chapter" data-level="5.16.1" data-path="N.html"><a href="N.html#error-could-not-find-function-ode"><i class="fa fa-check"></i><b>5.16.1</b> Error: “could not find function ‘ode’”</a></li>
<li class="chapter" data-level="5.16.2" data-path="N.html"><a href="N.html#warning-lsoda-at-t-too-much-accuracy-requested"><i class="fa fa-check"></i><b>5.16.2</b> Warning: “lsoda– at t…, too much accuracy requested”</a></li>
<li class="chapter" data-level="5.16.3" data-path="N.html"><a href="N.html#graph-shows-exponential-explosion-or-negative-values"><i class="fa fa-check"></i><b>5.16.3</b> Graph shows exponential explosion or negative values</a></li>
<li class="chapter" data-level="5.16.4" data-path="N.html"><a href="N.html#model-doesnt-reach-equilibrium"><i class="fa fa-check"></i><b>5.16.4</b> Model doesn’t reach equilibrium</a></li>
<li class="chapter" data-level="5.16.5" data-path="N.html"><a href="N.html#pools-go-negative"><i class="fa fa-check"></i><b>5.16.5</b> Pools go negative</a></li>
</ul></li>
<li class="chapter" data-level="5.17" data-path="N.html"><a href="N.html#connections-to-previous-chapters"><i class="fa fa-check"></i><b>5.17</b> Connections to Previous Chapters</a></li>
<li class="chapter" data-level="5.18" data-path="N.html"><a href="N.html#summary-and-key-takeaways"><i class="fa fa-check"></i><b>5.18</b> Summary and Key Takeaways</a></li>
<li class="chapter" data-level="5.19" data-path="N.html"><a href="N.html#references"><i class="fa fa-check"></i><b>5.19</b> References</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="lake-metabolism.html"><a href="lake-metabolism.html"><i class="fa fa-check"></i><b>6</b> Lake Metabolism</a>
<ul>
<li class="chapter" data-level="6.1" data-path="lake-metabolism.html"><a href="lake-metabolism.html#estimating-productivity"><i class="fa fa-check"></i><b>6.1</b> Estimating Productivity</a></li>
<li class="chapter" data-level="6.2" data-path="lake-metabolism.html"><a href="lake-metabolism.html#by-hand-but-in-r"><i class="fa fa-check"></i><b>6.2</b> By hand, but in R</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="lake-metabolism.html"><a href="lake-metabolism.html#plot-one-cycle"><i class="fa fa-check"></i><b>6.2.1</b> Plot one cycle</a></li>
<li class="chapter" data-level="6.2.2" data-path="lake-metabolism.html"><a href="lake-metabolism.html#average-of-all-nights"><i class="fa fa-check"></i><b>6.2.2</b> Average of all nights</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="lake-metabolism.html"><a href="lake-metabolism.html#the-lakemetabolizer-package"><i class="fa fa-check"></i><b>6.3</b> The LakeMetabolizer package</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="npzd---a-simple-aquatic-ecosystem.html"><a href="npzd---a-simple-aquatic-ecosystem.html"><i class="fa fa-check"></i><b>7</b> NPZD - a simple aquatic ecosystem</a>
<ul>
<li class="chapter" data-level="7.1" data-path="npzd---a-simple-aquatic-ecosystem.html"><a href="npzd---a-simple-aquatic-ecosystem.html#this-task"><i class="fa fa-check"></i><b>7.1</b> This task</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="npzd---a-simple-aquatic-ecosystem.html"><a href="npzd---a-simple-aquatic-ecosystem.html#create-an-r-script-of-npzd"><i class="fa fa-check"></i><b>7.1.1</b> Create an R script of NPZD</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="model-sensitivity.html"><a href="model-sensitivity.html"><i class="fa fa-check"></i><b>8</b> Model Sensitivity</a>
<ul>
<li class="chapter" data-level="8.1" data-path="model-sensitivity.html"><a href="model-sensitivity.html#types-of-sensitivity"><i class="fa fa-check"></i><b>8.1</b> Types of Sensitivity</a></li>
<li class="chapter" data-level="8.2" data-path="model-sensitivity.html"><a href="model-sensitivity.html#local-sensitivity"><i class="fa fa-check"></i><b>8.2</b> Local sensitivity</a></li>
<li class="chapter" data-level="8.3" data-path="model-sensitivity.html"><a href="model-sensitivity.html#assessing-sensitivity-in-a-nitrogen-budget-model"><i class="fa fa-check"></i><b>8.3</b> Assessing sensitivity in a nitrogen budget model</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="model-sensitivity.html"><a href="model-sensitivity.html#dynamics-of-sensitivity-in-one-state-variable"><i class="fa fa-check"></i><b>8.3.1</b> Dynamics of sensitivity in one state variable</a></li>
<li class="chapter" data-level="8.3.2" data-path="model-sensitivity.html"><a href="model-sensitivity.html#summary-of-sensitivities-in-all-state-variables"><i class="fa fa-check"></i><b>8.3.2</b> Summary of sensitivities in all state variables</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="model-sensitivity.html"><a href="model-sensitivity.html#sensitivity-in-an-aquatic-ecosystem"><i class="fa fa-check"></i><b>8.4</b> Sensitivity in an aquatic ecosystem</a></li>
<li class="chapter" data-level="8.5" data-path="model-sensitivity.html"><a href="model-sensitivity.html#letting-sensitivity-analysis-guide-next-steps"><i class="fa fa-check"></i><b>8.5</b> Letting Sensitivity Analysis Guide Next Steps</a></li>
<li class="chapter" data-level="8.6" data-path="model-sensitivity.html"><a href="model-sensitivity.html#your-turn"><i class="fa fa-check"></i><b>8.6</b> Your turn</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="MEL.html"><a href="MEL.html"><i class="fa fa-check"></i><b>9</b> Multiple Element Limitation</a>
<ul>
<li class="chapter" data-level="9.1" data-path="MEL.html"><a href="MEL.html#rastetter-et-al.-1997"><i class="fa fa-check"></i><b>9.1</b> Rastetter et al. 1997</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="MEL.html"><a href="MEL.html#the-model"><i class="fa fa-check"></i><b>9.1.1</b> The model</a></li>
<li class="chapter" data-level="9.1.2" data-path="MEL.html"><a href="MEL.html#parameters"><i class="fa fa-check"></i><b>9.1.2</b> Parameters</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="MEL.html"><a href="MEL.html#implementing-mel"><i class="fa fa-check"></i><b>9.2</b> Implementing MEL</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="MEL.html"><a href="MEL.html#increasing-atmospheric-carbon-with-events-in-ode"><i class="fa fa-check"></i><b>9.2.1</b> Increasing atmospheric carbon with events in <code>ode()</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="optimization.html"><a href="optimization.html"><i class="fa fa-check"></i><b>10</b> Optimization</a>
<ul>
<li class="chapter" data-level="10.1" data-path="optimization.html"><a href="optimization.html#introduction"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="optimization.html"><a href="optimization.html#bormann-logistic-model"><i class="fa fa-check"></i><b>10.2</b> Bormann logistic model</a></li>
<li class="chapter" data-level="10.3" data-path="optimization.html"><a href="optimization.html#fitting-a-model-to-data"><i class="fa fa-check"></i><b>10.3</b> Fitting a model to data</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="optimization.html"><a href="optimization.html#minimization"><i class="fa fa-check"></i><b>10.3.1</b> Minimization</a></li>
<li class="chapter" data-level="10.3.2" data-path="optimization.html"><a href="optimization.html#creating-the-objective-function"><i class="fa fa-check"></i><b>10.3.2</b> Creating the objective function</a></li>
<li class="chapter" data-level="10.3.3" data-path="optimization.html"><a href="optimization.html#optim"><i class="fa fa-check"></i><b>10.3.3</b> <code>optim()</code></a></li>
<li class="chapter" data-level="10.3.4" data-path="optimization.html"><a href="optimization.html#mle2"><i class="fa fa-check"></i><b>10.3.4</b> <code>mle2()</code></a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="optimization.html"><a href="optimization.html#trajectory-matching"><i class="fa fa-check"></i><b>10.4</b> Trajectory matching</a></li>
<li class="chapter" data-level="10.5" data-path="optimization.html"><a href="optimization.html#two-or-more-parameters-at-a-time"><i class="fa fa-check"></i><b>10.5</b> Two (or more) parameters at a time</a></li>
<li class="chapter" data-level="10.6" data-path="optimization.html"><a href="optimization.html#other-considerations-weighting-deviations"><i class="fa fa-check"></i><b>10.6</b> Other considerations: weighting deviations</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="optimization.html"><a href="optimization.html#variance-weighted-errors"><i class="fa fa-check"></i><b>10.6.1</b> Variance weighted errors</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="more-on-forcing-functions-using-data-inside-models.html"><a href="more-on-forcing-functions-using-data-inside-models.html"><i class="fa fa-check"></i><b>11</b> More On Forcing Functions: Using data inside models</a>
<ul>
<li class="chapter" data-level="11.1" data-path="more-on-forcing-functions-using-data-inside-models.html"><a href="more-on-forcing-functions-using-data-inside-models.html#preliminaries"><i class="fa fa-check"></i><b>11.1</b> Preliminaries</a></li>
<li class="chapter" data-level="11.2" data-path="more-on-forcing-functions-using-data-inside-models.html"><a href="more-on-forcing-functions-using-data-inside-models.html#n-deposition"><i class="fa fa-check"></i><b>11.2</b> N deposition</a></li>
<li class="chapter" data-level="11.3" data-path="more-on-forcing-functions-using-data-inside-models.html"><a href="more-on-forcing-functions-using-data-inside-models.html#denitrification"><i class="fa fa-check"></i><b>11.3</b> Denitrification</a></li>
<li class="chapter" data-level="11.4" data-path="more-on-forcing-functions-using-data-inside-models.html"><a href="more-on-forcing-functions-using-data-inside-models.html#annual-temperature-as-a-forcing-function"><i class="fa fa-check"></i><b>11.4</b> Annual temperature as a forcing function</a></li>
<li class="chapter" data-level="11.5" data-path="more-on-forcing-functions-using-data-inside-models.html"><a href="more-on-forcing-functions-using-data-inside-models.html#in-fine"><i class="fa fa-check"></i><b>11.5</b> In fine</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="appendix-build-a-model-of-your-own-system.html"><a href="appendix-build-a-model-of-your-own-system.html"><i class="fa fa-check"></i><b>12</b> Appendix: Build a model of your own system</a>
<ul>
<li class="chapter" data-level="12.1" data-path="appendix-build-a-model-of-your-own-system.html"><a href="appendix-build-a-model-of-your-own-system.html#background-readings-1"><i class="fa fa-check"></i><b>12.1</b> Background Readings:</a></li>
<li class="chapter" data-level="12.2" data-path="appendix-build-a-model-of-your-own-system.html"><a href="appendix-build-a-model-of-your-own-system.html#steps"><i class="fa fa-check"></i><b>12.2</b> Steps</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="references-1.html"><a href="references-1.html"><i class="fa fa-check"></i><b>13</b> References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Primer of Ecosystem Modeling - a work in progress</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="N" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">5</span> Describing a nitrogen budget<a href="N.html#N" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="learning-objectives-2" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Learning Objectives<a href="N.html#learning-objectives-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>By the end of this chapter, you should be able to:</p>
<ul>
<li>Translate a published nitrogen budget into a compartment model diagram</li>
<li>Write balance equations for multi-compartment systems with mixed rate types</li>
<li>Distinguish between first-order and zero-order fluxes in a real ecosystem</li>
<li>Estimate model parameters from literature data using both incremental and instantaneous rate methods</li>
<li>Understand why we use instantaneous rates in differential equations</li>
<li>Implement and run a multi-compartment model in R</li>
<li>Interpret model output in terms of ecosystem dynamics and equilibrium states</li>
<li>Add self-limitation to represent biological constraints on growth</li>
</ul>
</div>
<div id="background-readings" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Background Readings<a href="N.html#background-readings" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>pp. 17-35 (Soetaert and Hermann 2009)</li>
<li>Bormann et al. 1977. Nitrogen Budget for an aggrading northern hardwood forest ecosystem. <em>Science</em> 196:981-983.</li>
</ul>
<div class="figure"><span style="display:block;" id="fig:hbnb0"></span>
<img src="figs/BormannF2.png" alt="*Nitrogen budget for a temperate northern hardwood forest (Hubbard Brook Watershed 6, Bormann et al. 1977).*" width="100%" />
<p class="caption">
Figure 5.1: <em>Nitrogen budget for a temperate northern hardwood forest (Hubbard Brook Watershed 6, Bormann et al. 1977).</em>
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:hbnb3"></span>
<img src="figs/model3.png" alt="*A simpler compartment model for Hubbard Brook Watershed 6, based on Bormann et al. (1977).*" width="75%" />
<p class="caption">
Figure 5.2: <em>A simpler compartment model for Hubbard Brook Watershed 6, based on Bormann et al. (1977).</em>
</p>
</div>
</div>
<div id="understanding-the-hubbard-brook-system" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Understanding the Hubbard Brook System<a href="N.html#understanding-the-hubbard-brook-system" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before we dive into the mathematics, let’s think about what’s actually happening in this forest ecosystem. Hubbard Brook is a classic study site where ecologists have tracked nutrient cycling in a northern hardwood forest for decades. This particular watershed (Watershed 6) was recovering from logging - an <em>aggrading</em> forest actively accumulating biomass and nutrients.</p>
<p><strong>The vegetation compartment (V)</strong> represents all living plant tissue - leaves, wood, fine roots. Plants are actively taking up nitrogen from the soil to build proteins and other molecules. As this forest regrows, the vegetation pool is increasing.</p>
<p><strong>The available pool (A)</strong> is nitrogen in forms plants can use immediately - primarily ammonium (NH₄⁺) and nitrate (NO₃⁻) dissolved in soil water. This pool is relatively small but turns over quickly. Think of it as the “checking account” that plants draw from.</p>
<p><strong>The bound pool (B)</strong> is organic nitrogen locked up in dead organic matter - fallen leaves, dead roots, humus. This is the largest pool but changes slowly - like a “savings account” that releases nutrients gradually through decomposition. Most of the forest’s nitrogen is stored here.</p>
<p><strong>Key insight:</strong> Not all fluxes operate the same way. Some depend on how much material is available (first-order kinetics), while others are more constant (zero-order kinetics). Recall from Chapters <a href="simple-budgets.html#simple-budgets">2</a> and <a href="first-order-compartments.html#first-order-compartments">3</a> that we learned about both types. This real ecosystem combines both. As we build our model, think about which biological processes fit each pattern.</p>
</div>
<div id="getting-started" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Getting started<a href="N.html#getting-started" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li>(S&amp;H 15-17) For any ecosystem, we want to start with paper and pencil and <strong>sketch out the pools and the fluxes</strong> that we think are important (see example, Fig. <a href="N.html#fig:hbnb3">5.2</a>). Don’t sweat the details yet – you’ll revise it anyway. Go ahead and label the compartments and the fluxes with both biological and physical processes as well as some simple abstract notation.</li>
</ol>
</div>
<div id="classifying-the-fluxes" class="section level2 hasAnchor" number="5.5">
<h2><span class="header-section-number">5.5</span> Classifying the Fluxes<a href="N.html#classifying-the-fluxes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before writing balance equations, let’s classify each flux by its kinetics. This connects directly to what you learned in the previous chapters.</p>
<p><strong>Zero-order (constant) fluxes:</strong></p>
<ul>
<li><strong>Bulk precipitation (I₁):</strong> Rain and snow deposit nitrogen regardless of how much N is already in the forest. This is an external input to the system.</li>
<li><strong>N fixation (I₂):</strong> Symbiotic bacteria in root nodules convert atmospheric N₂ to usable forms. The rate depends on bacterial activity and environmental conditions, not on existing forest N pools.</li>
</ul>
<p><strong>First-order (mass-dependent) fluxes:</strong></p>
<ul>
<li><strong>Plant uptake (f₁):</strong> Depends on both available N (more available = faster uptake) and plant biomass (more roots = more uptake capacity). This is a second-order interaction: f₁ = function(A,V).</li>
<li><strong>Throughfall/exudates (f₂):</strong> Rain washes N out of leaves and roots release organic compounds. Proportional to vegetation biomass: more vegetation = more throughfall.</li>
<li><strong>Litterfall (f₃):</strong> Leaf and root senescence. Proportional to vegetation biomass - larger forests produce more litter.</li>
<li><strong>Mineralization (f₄):</strong> Decomposers break down organic matter, releasing available N. Rate depends on how much organic matter is present - more substrate = faster mineralization.</li>
<li><strong>Stream export from A (E₁):</strong> Dissolved N washes out with streamflow. Proportional to concentration, which depends on pool size.</li>
<li><strong>Stream export from B (E₂):</strong> Particulate organic matter washed downstream. Proportional to the bound pool.</li>
</ul>
<p><strong>Why does this matter?</strong> The mathematical form of each term in our equations will match its kinetic type. Recognizing this pattern helps you write the equations correctly and understand why they have the forms they do. Zero-order processes appear as constants in equations; first-order processes appear as rate constant × pool size.</p>
<div id="quick-check-1" class="section level3 hasAnchor" number="5.5.1">
<h3><span class="header-section-number">5.5.1</span> Quick Check 1<a href="N.html#quick-check-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Before moving on, make sure you understand:</p>
<ol style="list-style-type: decimal">
<li>Which fluxes in Figure <a href="N.html#fig:hbnb3">5.2</a> are external to the three-compartment system (cross system boundaries)?</li>
<li>Which fluxes are internal transfers (stay within the system)?</li>
<li>For each internal flux, which compartment is the source and which is the sink?</li>
</ol>
<details>
<summary>
<strong>Click for answers</strong>
</summary>
<p><strong>External inputs:</strong> I₁ (precipitation to A), I₂ (fixation to B)</p>
<p><strong>External outputs:</strong> E₁ (export from A), E₂ (export from B)</p>
<p><strong>Internal transfers:</strong>
- f₁: from A to V (plant uptake)
- f₂: from V to A (throughfall/exudates)
- f₃: from V to B (litterfall)
- f₄: from B to A (mineralization)</p>
</details>
</div>
</div>
<div id="write-balance-equations" class="section level2 hasAnchor" number="5.6">
<h2><span class="header-section-number">5.6</span> Write Balance Equations<a href="N.html#write-balance-equations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Recall from Chapter <a href="intro.html#intro">4</a> that a balance equation is simply: <strong>Change in pool = Sources - Sinks</strong></p>
<p>For each compartment, we identify all arrows entering (sources) and leaving (sinks), then write the rate equation. Here are the balance equations for Fig. <a href="N.html#fig:hbnb3">5.2</a>:</p>
<p><strong>Rate of change of vegetation</strong> = uptake - exudates and throughfall - leaf and root litter loss
<span class="math display">\[\frac{dV}{dt} = f_1 - f_2 - f_3\]</span></p>
<p><strong>Rate of change in available pool</strong> = bulk precip + exudates and throughfall + net mineralization - uptake - stream export
<span class="math display">\[\frac{dA}{dt} = I_1 + f_2 + f_4 - f_1 - E_1\]</span></p>
<p><strong>Rate of change in the bound pool</strong> = net N fixation + leaf and root litter loss - net mineralization - stream export
<span class="math display">\[\frac{dB}{dt} = I_2 + f_3 - f_4 - E_2\]</span></p>
<div id="quick-check-2" class="section level3 hasAnchor" number="5.6.1">
<h3><span class="header-section-number">5.6.1</span> Quick Check 2<a href="N.html#quick-check-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Before looking ahead:</p>
<ol style="list-style-type: decimal">
<li><p>For the vegetation equation, identify which terms represent:</p>
<ul>
<li>Gains to the pool</li>
<li>Losses from the pool</li>
<li>Transfers within the system vs. external inputs/outputs</li>
</ul></li>
<li><p>Sum all three balance equations. What should cancel out? What should remain?</p></li>
<li><p>Does this match the total mass budget we’ll show next?</p></li>
</ol>
<details>
<summary>
<strong>Click for answers</strong>
</summary>
<ol style="list-style-type: decimal">
<li><p><strong>Gains:</strong> f₁ (internal transfer from A); <strong>Losses:</strong> f₂ and f₃ (internal transfers to A and B); <strong>External:</strong> none for vegetation - it only exchanges with other compartments, not with outside the system</p></li>
<li><p>When you sum the three equations, all internal fluxes (f₁, f₂, f₃, f₄) should appear once positive and once negative, so they cancel. Only external inputs and outputs remain.</p></li>
<li><p>Yes! See the next section.</p></li>
</ol>
</details>
</div>
</div>
<div id="assess-the-total-system-budget" class="section level2 hasAnchor" number="5.7">
<h2><span class="header-section-number">5.7</span> Assess the Total System Budget<a href="N.html#assess-the-total-system-budget" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For Fig. <a href="N.html#fig:hbnb3">5.2</a>, we have the total rate of change for the entire system:</p>
<p><span class="math display">\[\frac{d\left(V+A+B\right)}{dt} = \frac{dV}{dt} + \frac{dA}{dt} + \frac{dB}{dt}\]</span></p>
<p>Substituting our balance equations:</p>
<p><span class="math display">\[\frac{d\left(V+A+B\right)}{dt} = (f_1 - f_2 - f_3) + (I_1 + f_2 + f_4 - f_1 - E_1) + (I_2 + f_3 - f_4 - E_2)\]</span></p>
<p>Now watch what happens when we rearrange and cancel terms:</p>
<p><span class="math display">\[\frac{d\left(V+A+B\right)}{dt} = I_1 + I_2 + f_1 - f_1 + f_2 - f_2 + f_3 - f_3  + f_4 - f_4 - E_1 - E_2\]</span></p>
<p>All the internal fluxes cancel (this is the key feature of mass balance!):</p>
<p><span class="math display">\[\frac{d\left(V+A+B\right)}{dt} = I_1 + I_2 - E_1 - E_2\]</span></p>
<p><strong>From this we see that the total mass budget for this watershed depends simply on imports (inputs) and exports (outputs).</strong> The internal cycling doesn’t affect the total - it just redistributes nitrogen among compartments. This is a powerful check on our model - if the internal fluxes don’t cancel when we sum everything, we made a mistake!</p>
</div>
<div id="mathematical-forms-for-fluxes" class="section level2 hasAnchor" number="5.8">
<h2><span class="header-section-number">5.8</span> Mathematical Forms for Fluxes<a href="N.html#mathematical-forms-for-fluxes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now we need to express each flux as a mathematical function. Recall from earlier that we classified fluxes as zero-order or first-order. Now we make that explicit.</p>
<p><strong>For zero-order (constant) fluxes:</strong></p>
<p>These are simply constants. From the data:
- I₁ = 6.5 kg N ha⁻¹ y⁻¹ (precipitation)
- I₂ = 14.2 kg N ha⁻¹ y⁻¹ (fixation)</p>
<p><strong>For first-order fluxes:</strong></p>
<p>A common starting point for dynamics depending on pool sizes is the <strong>law of mass action</strong>. This states that the reaction rate is proportional to the amount of substrate present in a single pool.</p>
<p>For a flux depending on one pool: <strong>flux = k × Pool</strong></p>
<p><strong>For second-order fluxes:</strong></p>
<p>A flux is <em>second-order</em> when a rate is proportional to either two pools (<span class="math inline">\(XY\)</span>), or to the the square of one pool (<span class="math inline">\(X^2\)</span>). This still relies ofn the law of <strong>law of mass action</strong>.</p>
<p>For a flux depending on two pools: <strong>flux = k × Pool₁ × Pool₂</strong></p>
<p>Using mass action kinetics, we express the fluxes in our N budget (Fig. <a href="N.html#fig:hbnb3">5.2</a>) as:</p>
<ul>
<li><strong>f₁</strong> (uptake): depends on both A and V → f₁ = a₁ × A × V</li>
<li><strong>f₂</strong> (throughfall/exudates): depends on V → f₂ = a₂ × V<br />
</li>
<li><strong>f₃</strong> (litterfall): depends on V → f₃ = a₃ × V</li>
<li><strong>f₄</strong> (mineralization): depends on B → f₄ = a₄ × B</li>
<li><strong>E₁</strong> (export from A): depends on A → E₁ = a₅ × A</li>
<li><strong>E₂</strong> (export from B): depends on B → E₂ = a₆ × B</li>
</ul>
<div id="complete-balance-equations" class="section level3 hasAnchor" number="5.8.1">
<h3><span class="header-section-number">5.8.1</span> Complete Balance Equations<a href="N.html#complete-balance-equations" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Substituting these mathematical forms into our balance equations:</p>
<p><span class="math display">\[\begin{align}
\frac{dV}{dt} &amp;= a_{1}AV - a_{2}V - a_3 V\\
\frac{dA}{dt} &amp;= I_1 + a_{2}V +  a_{4}B - a_{1}AV - a_{5}A\\
\frac{dB}{dt} &amp;= I_2 + a_{3}V - a_{4}B - a_{6}B
\end{align}\]</span></p>
<p>Take time to identify each term and think about the biology or physics that might govern it. For instance, why does uptake depend on both A and V? Because you need both nutrients available AND plant tissue capable of taking them up.</p>
</div>
</div>
<div id="a-critical-detail-consistent-sign-conventions" class="section level2 hasAnchor" number="5.9">
<h2><span class="header-section-number">5.9</span> A Critical Detail: Consistent Sign Conventions<a href="N.html#a-critical-detail-consistent-sign-conventions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before we estimate parameters, we need to address an important mathematical detail that can cause confusion.</p>
<p><strong>The challenge:</strong> When we estimate parameters from loss fluxes using real data, we often get negative numbers (because the pool is declining). But when we write equations, we need to be careful about signs.</p>
<p><strong>Two approaches:</strong></p>
<p><strong>Option 1 - Keep the signs in the parameters:</strong></p>
<pre><code>a₄ = -0.0149  # negative because it&#39;s a loss from B
dB/dt = ... + a₄*B  # add the negative rate</code></pre>
<p><strong>Option 2 - Use absolute values (we’ll use this):</strong></p>
<pre><code>a₄ = 0.0149  # store as positive magnitude
dB/dt = ... - a₄*B  # subtract explicitly in equation</code></pre>
<p><strong>Why Option 2?</strong> It makes the biology clearer in our equations. When we see “- a₄ × B” in the equation for dB/dt, we immediately know this is a loss from B. The signs in our equations match our conceptual diagram - sources have + signs, sinks have - signs.</p>
<p><strong>Our rule:</strong> We’ll calculate the <em>magnitude</em> (absolute value) of all rate constants and use +/- signs in equations to show direction of transfer. This matches the visual logic of our box-and-arrow diagrams.</p>
</div>
<div id="parameterization" class="section level2 hasAnchor" number="5.10">
<h2><span class="header-section-number">5.10</span> Parameterization<a href="N.html#parameterization" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Parameterization is what we call assigning numerical values to mathematical parameters. Here, we find initial estimates for the parameters in our model. We use the literature for this purpose <span class="citation">(<a href="#ref-bormann1977">Bormann, Likens, and Melillo 1977</a>)</span>.</p>
<p>The data from Bormann et al. give us annual fluxes (kg N ha⁻¹ y⁻¹) and pool sizes (kg N ha⁻¹). Our job is to convert these observations into rate constants.</p>
<div id="the-challenge-annual-rates-vs.-instantaneous-rates" class="section level3 hasAnchor" number="5.10.1">
<h3><span class="header-section-number">5.10.1</span> The Challenge: Annual Rates vs. Instantaneous Rates<a href="N.html#the-challenge-annual-rates-vs.-instantaneous-rates" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>The problem we face:</strong> Our data from Bormann give us <em>annual budgets</em> - total amounts that moved over one year. But differential equations describe <em>instantaneous rates</em> - how fast things are changing at any given moment in time.</p>
<p><strong>An analogy to clarify this:</strong></p>
<p>Imagine you’re driving. Your odometer shows you drove 60 miles in one hour - that’s like an annual rate, total distance over total time. But you didn’t drive exactly 60 mph the entire time - you accelerated from stoplights, slowed in traffic, cruised on the highway. Your speedometer shows your <em>instantaneous</em> speed at each moment - that’s what we need for differential equations.</p>
<p><strong>In our model:</strong></p>
<p>If the bound pool loses 69.6 kg N ha⁻¹ year⁻¹ to mineralization, we can’t just write:</p>
<p><span class="math display">\[\frac{dB}{dt} = \ldots - 69.6\]</span></p>
<p>Why not? Two reasons:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Units don’t match:</strong> The left side has units of kg ha⁻¹ y⁻¹, but we said the flux depends on pool size: f₄ = a₄ × B. If B has units of kg ha⁻¹, then a₄ must have units of y⁻¹ (per year), not kg ha⁻¹ y⁻¹.</p></li>
<li><p><strong>The rate changes:</strong> As the pool shrinks or grows during the year, the actual rate of loss changes if the flux is proportional to pool size. We need the <em>instantaneous</em> proportionality constant, not the average annual flux.</p></li>
</ol>
<p><strong>Two approaches to estimate rate constants:</strong></p>
</div>
<div id="approach-1-annual-incremental-rates-simpler" class="section level3 hasAnchor" number="5.10.2">
<h3><span class="header-section-number">5.10.2</span> Approach 1: Annual Incremental Rates (Simpler)<a href="N.html#approach-1-annual-incremental-rates-simpler" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For a simple approximation, we can calculate an annual incremental rate by dividing the annual flux by the pool size:</p>
<p><span class="math display">\[\text{rate constant} = \frac{\text{annual flux}}{\text{current pool size}}\]</span></p>
<p><strong>Example:</strong> Net mineralization from the bound pool</p>
<p>The bound pool (B) loses 69.6 kg N ha⁻¹ y⁻¹ to mineralization, and currently contains 4,700 kg N ha⁻¹.</p>
<p><span class="math display">\[\begin{align*}
  F_4 &amp;= a_4 B\\
  69.6 &amp;= a_4 \times 4700\\
  a_4 &amp;= \frac{69.6}{4700}\\
  a_4 &amp;\approx 0.0148 \text{ y}^{-1}
\end{align*}\]</span></p>
<p><strong>Example:</strong> Plant uptake (second-order reaction)</p>
<p>We use the same approach for second-order equations. The vegetation gains 79.6 kg N ha⁻¹ y⁻¹ through uptake. The available pool contains 26 kg N ha⁻¹ and vegetation contains 532 kg N ha⁻¹.</p>
<p><span class="math display">\[\begin{align*}
  F_1 &amp;= a_1 AV \\
  79.6 &amp;= a_1 \times 26 \times 532  \\
  a_1 &amp;= \frac{79.6}{26 \times 532}\\
  a_1 &amp;\approx 0.0058 \text{ (kg ha}^{-1})^{-1} \text{y}^{-1}
\end{align*}\]</span></p>
<p>Note the units! For a second-order rate constant, we have (kg ha⁻¹)⁻¹ y⁻¹, which makes the units work out when we multiply by two pools.</p>
</div>
<div id="approach-2-instantaneous-rates-using-logarithms-more-accurate" class="section level3 hasAnchor" number="5.10.3">
<h3><span class="header-section-number">5.10.3</span> Approach 2: Instantaneous Rates Using Logarithms (More Accurate)<a href="N.html#approach-2-instantaneous-rates-using-logarithms-more-accurate" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For a more accurate approach that properly handles the continuous nature of differential equations, we use logarithms. This approach gives us true instantaneous rate constants.</p>
<p><strong>The mathematical basis:</strong></p>
<p>If a pool changes continuously at a rate proportional to its size, then:</p>
<p><span class="math display">\[\text{instantaneous rate constant} = \ln\left(\frac{\text{pool after change}}{\text{pool before change}}\right)\]</span></p>
<p>For our system, if we imagine the pool over one year with only one flux operating:</p>
<p><strong>Example:</strong> Net mineralization (loss from bound pool)</p>
<p>Let B₀ be the mass of N in the bound pool at time 0, and B₁ would be the mass one year later if we account for only the mineralization flux coming out of B:</p>
<p><span class="math display">\[B_0=4700 \quad ; \quad B_1 = B_0 - F_4 = 4700 - 69.6 = 4630.4\]</span></p>
<p>The instantaneous rate constant α₄ required to get us from B₀ to B₁ in one year is:</p>
<p><span class="math display">\[\alpha_4 = \ln\left(\frac{B_1}{B_0}\right) =  \ln\left(\frac{4700-69.6}{4700}\right) \approx -0.0149 \text{ y}^{-1}\]</span></p>
<p><strong>Notice:</strong> This gives us a <em>negative</em> number because the pool is declining. Following our sign convention from earlier, we’ll take the absolute value and use subtraction in the equation.</p>
<p><strong>Comparing the two approaches:</strong></p>
<ul>
<li>Annual incremental: a₄ = 0.0148 y⁻¹</li>
<li>Instantaneous: |α₄| = 0.0149 y⁻¹</li>
</ul>
<p>They’re very similar! For small changes relative to pool size, the two approaches give nearly identical results. However, for larger fractional changes, the instantaneous rate is more accurate for use in differential equations.</p>
<p><strong>Why use logarithms?</strong> This comes from calculus. When a quantity changes exponentially (like radioactive decay or first-order chemical reactions), the instantaneous rate constant is exactly ln(final/initial) per unit time. Since our differential equations assume continuous exponential-like change, this is the theoretically correct approach.</p>
</div>
<div id="quick-check-3" class="section level3 hasAnchor" number="5.10.4">
<h3><span class="header-section-number">5.10.4</span> Quick Check 3<a href="N.html#quick-check-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Before looking at the full parameter table, try this yourself:</p>
<p>Calculate the parameter for throughfall and exudates (a₂) using both approaches:</p>
<ul>
<li>Annual flux from V to A: 6.6 + 0.8 = 7.4 kg N ha⁻¹ y⁻¹</li>
<li>Current vegetation: 532 kg N ha⁻¹</li>
<li>Show your work for both the incremental and instantaneous approaches</li>
<li>Don’t forget the sign convention!</li>
</ul>
<details>
<summary>
<strong>Click for answers</strong>
</summary>
<p><strong>Incremental approach:</strong>
<span class="math display">\[a_2 = \frac{7.4}{532} = 0.0139 \text{ y}^{-1}\]</span></p>
<p><strong>Instantaneous approach:</strong>
<span class="math display">\[\alpha_2 = \left|\ln\left(\frac{532 - 7.4}{532}\right)\right| = \left|\ln(0.9861)\right| = |-0.0140| = 0.0140 \text{ y}^{-1}\]</span></p>
<p>Again, very similar values!</p>
</details>
</div>
</div>
<div id="calculating-all-parameters-in-r" class="section level2 hasAnchor" number="5.11">
<h2><span class="header-section-number">5.11</span> Calculating All Parameters in R<a href="N.html#calculating-all-parameters-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now let’s calculate all our parameters systematically. Following our sign convention, we’ll compute absolute values and use the instantaneous rate approach (logarithmic method).</p>
<p><strong>Throughfall and inorganic exudates</strong> - a loss from vegetation, so we use absolute value:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="N.html#cb10-1" tabindex="-1"></a><span class="co"># Annual flux from V to A: 6.6 + 0.8 = 7.4 kg N/ha/y</span></span>
<span id="cb10-2"><a href="N.html#cb10-2" tabindex="-1"></a>a2 <span class="ot">&lt;-</span> <span class="fu">abs</span>( <span class="fu">log</span>( (<span class="dv">532</span> <span class="sc">-</span> <span class="fl">6.6</span> <span class="sc">-</span> <span class="fl">0.8</span>) <span class="sc">/</span> <span class="dv">532</span> ) )</span>
<span id="cb10-3"><a href="N.html#cb10-3" tabindex="-1"></a>a2</span></code></pre></div>
<pre><code>## [1] 0.01400742</code></pre>
<p><strong>Litter, throughfall, organic exudates</strong> - a loss from vegetation to bound pool:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="N.html#cb12-1" tabindex="-1"></a><span class="co"># Annual flux from V to B: 54.2 + 2.7 + 0.1 + 6.2 = 63.2 kg N/ha/y</span></span>
<span id="cb12-2"><a href="N.html#cb12-2" tabindex="-1"></a>a3 <span class="ot">&lt;-</span> <span class="fu">abs</span>( <span class="fu">log</span>( (<span class="dv">532</span> <span class="sc">-</span> <span class="fl">54.2</span> <span class="sc">-</span> <span class="fl">2.7</span> <span class="sc">-</span> <span class="fl">0.1</span> <span class="sc">-</span> <span class="fl">6.2</span>) <span class="sc">/</span> <span class="dv">532</span>) )</span>
<span id="cb12-3"><a href="N.html#cb12-3" tabindex="-1"></a>a3</span></code></pre></div>
<pre><code>## [1] 0.1264673</code></pre>
<p><strong>Net mineralization</strong> - a loss from the bound pool:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="N.html#cb14-1" tabindex="-1"></a><span class="co"># Annual flux from B to A: 69.6 kg N/ha/y</span></span>
<span id="cb14-2"><a href="N.html#cb14-2" tabindex="-1"></a>a4 <span class="ot">&lt;-</span>  <span class="fu">abs</span>( <span class="fu">log</span>( (<span class="dv">4700</span> <span class="sc">-</span> <span class="fl">69.6</span>) <span class="sc">/</span> <span class="dv">4700</span>) )</span>
<span id="cb14-3"><a href="N.html#cb14-3" tabindex="-1"></a>a4</span></code></pre></div>
<pre><code>## [1] 0.01491925</code></pre>
<p><strong>Export from the available pool</strong> - a loss:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="N.html#cb16-1" tabindex="-1"></a><span class="co"># Annual export: 3.9 kg N/ha/y</span></span>
<span id="cb16-2"><a href="N.html#cb16-2" tabindex="-1"></a>a5 <span class="ot">&lt;-</span> <span class="fu">abs</span>( <span class="fu">log</span>( (<span class="dv">26</span> <span class="sc">-</span> <span class="fl">3.9</span>) <span class="sc">/</span> <span class="dv">26</span> ) )</span>
<span id="cb16-3"><a href="N.html#cb16-3" tabindex="-1"></a>a5</span></code></pre></div>
<pre><code>## [1] 0.1625189</code></pre>
<p><strong>Export from the bound pool</strong> - a loss:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="N.html#cb18-1" tabindex="-1"></a><span class="co"># Annual export: 0.1 kg N/ha/y (very small)</span></span>
<span id="cb18-2"><a href="N.html#cb18-2" tabindex="-1"></a>a6 <span class="ot">&lt;-</span> <span class="fu">abs</span>( <span class="fu">log</span>( (<span class="dv">4700</span> <span class="sc">-</span> <span class="fl">0.1</span>) <span class="sc">/</span> <span class="dv">4700</span>) )</span>
<span id="cb18-3"><a href="N.html#cb18-3" tabindex="-1"></a>a6</span></code></pre></div>
<pre><code>## [1] 2.127682e-05</code></pre>
<p><strong>N Uptake by plants</strong> - a gain to vegetation that depends on both the source ($<span class="math inline">\() and sink (\)</span>V<span class="math inline">\(), making it a second order rate. This makes the rate more difficult to approximate, because the flux simply moves from one pool (\)</span>A<span class="math inline">\() to the other (\)</span>V<span class="math inline">\() and does not leave completely. Therefore, we will fall back on the incremental approach. In this case, the rate depends on the *product* of the the two pools (\)</span>AV$).</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="N.html#cb20-1" tabindex="-1"></a><span class="co"># Current state: V = 532, A = 26</span></span>
<span id="cb20-2"><a href="N.html#cb20-2" tabindex="-1"></a><span class="co"># Annual uptake flux: 79.6 kg N/ha/y</span></span>
<span id="cb20-3"><a href="N.html#cb20-3" tabindex="-1"></a>a1 <span class="ot">&lt;-</span> <span class="fl">79.6</span> <span class="sc">/</span> (<span class="dv">26</span> <span class="sc">*</span> <span class="dv">532</span>)</span>
<span id="cb20-4"><a href="N.html#cb20-4" tabindex="-1"></a>a1</span></code></pre></div>
<pre><code>## [1] 0.005754772</code></pre>
<p>Now we create a single vector of all parameters, including the constant inputs:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="N.html#cb22-1" tabindex="-1"></a>params <span class="ot">&lt;-</span> <span class="fu">c</span>( </span>
<span id="cb22-2"><a href="N.html#cb22-2" tabindex="-1"></a>  <span class="at">i1 =</span> <span class="fl">6.5</span>,   <span class="co"># bulk precipitation (kg N/ha/y)</span></span>
<span id="cb22-3"><a href="N.html#cb22-3" tabindex="-1"></a>  <span class="at">i2 =</span> <span class="fl">14.2</span>,  <span class="co"># N fixation (kg N/ha/y)</span></span>
<span id="cb22-4"><a href="N.html#cb22-4" tabindex="-1"></a>  <span class="at">a1 =</span> a1,    <span class="co"># uptake rate constant</span></span>
<span id="cb22-5"><a href="N.html#cb22-5" tabindex="-1"></a>  <span class="at">a2 =</span> a2,    <span class="co"># throughfall/exudates rate constant</span></span>
<span id="cb22-6"><a href="N.html#cb22-6" tabindex="-1"></a>  <span class="at">a3 =</span> a3,    <span class="co"># litterfall rate constant</span></span>
<span id="cb22-7"><a href="N.html#cb22-7" tabindex="-1"></a>  <span class="at">a4 =</span> a4,    <span class="co"># mineralization rate constant</span></span>
<span id="cb22-8"><a href="N.html#cb22-8" tabindex="-1"></a>  <span class="at">a5 =</span> a5,    <span class="co"># export from available pool</span></span>
<span id="cb22-9"><a href="N.html#cb22-9" tabindex="-1"></a>  <span class="at">a6 =</span> a6     <span class="co"># export from bound pool</span></span>
<span id="cb22-10"><a href="N.html#cb22-10" tabindex="-1"></a>)</span>
<span id="cb22-11"><a href="N.html#cb22-11" tabindex="-1"></a></span>
<span id="cb22-12"><a href="N.html#cb22-12" tabindex="-1"></a><span class="co"># Display with nice formatting</span></span>
<span id="cb22-13"><a href="N.html#cb22-13" tabindex="-1"></a><span class="fu">round</span>(params, <span class="dv">5</span>)</span></code></pre></div>
<pre><code>##       i1       i2       a1       a2       a3       a4       a5       a6 
##  6.50000 14.20000  0.00575  0.01401  0.12647  0.01492  0.16252  0.00002</code></pre>
<div id="parameter-table-with-biological-interpretation" class="section level3 hasAnchor" number="5.11.1">
<h3><span class="header-section-number">5.11.1</span> Parameter Table with Biological Interpretation<a href="N.html#parameter-table-with-biological-interpretation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<table class="table table-striped table-hover" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-15">Table 5.1: </span><span id="tab:unnamed-chunk-15">Table 5.2: </span>Parameters for simplified Hubbard Brook N budget model (Bormann et al. 1977). Values are instantaneous rate constants calculated using the logarithmic method. Note that a₆ is very small because export from the bound pool is minimal.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Parameter
</th>
<th style="text-align:left;">
Biological Meaning
</th>
<th style="text-align:center;">
Units
</th>
<th style="text-align:right;">
Estimate
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;background-color: rgba(240, 240, 240, 255) !important;">
<strong>State Variables</strong>
</td>
<td style="text-align:left;font-weight: bold;background-color: rgba(240, 240, 240, 255) !important;">
</td>
<td style="text-align:center;font-weight: bold;background-color: rgba(240, 240, 240, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;background-color: rgba(240, 240, 240, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:left;">
V
</td>
<td style="text-align:left;">
Living vegetation (leaves, wood, roots)
</td>
<td style="text-align:center;">
kg N ha⁻¹
</td>
<td style="text-align:right;">
532
</td>
</tr>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:left;">
Available N (NH₄⁺, NO₃⁻ in soil solution)
</td>
<td style="text-align:center;">
kg N ha⁻¹
</td>
<td style="text-align:right;">
26
</td>
</tr>
<tr>
<td style="text-align:left;">
B
</td>
<td style="text-align:left;">
Bound N (organic matter, humus)
</td>
<td style="text-align:center;">
kg N ha⁻¹
</td>
<td style="text-align:right;">
4700
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;background-color: rgba(240, 240, 240, 255) !important;">
<strong>Inputs (zero-order)</strong>
</td>
<td style="text-align:left;font-weight: bold;background-color: rgba(240, 240, 240, 255) !important;">
</td>
<td style="text-align:center;font-weight: bold;background-color: rgba(240, 240, 240, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;background-color: rgba(240, 240, 240, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:left;">
I₁
</td>
<td style="text-align:left;">
Bulk precipitation input to A
</td>
<td style="text-align:center;">
kg N ha⁻¹ y⁻¹
</td>
<td style="text-align:right;">
6.5
</td>
</tr>
<tr>
<td style="text-align:left;">
I₂
</td>
<td style="text-align:left;">
Biological N fixation input to B
</td>
<td style="text-align:center;">
kg N ha⁻¹ y⁻¹
</td>
<td style="text-align:right;">
14.2
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;background-color: rgba(240, 240, 240, 255) !important;">
<strong>Rate Constants (first-order)</strong>
</td>
<td style="text-align:left;font-weight: bold;background-color: rgba(240, 240, 240, 255) !important;">
</td>
<td style="text-align:center;font-weight: bold;background-color: rgba(240, 240, 240, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;background-color: rgba(240, 240, 240, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:left;">
a₁
</td>
<td style="text-align:left;">
Plant uptake: A → V (depends on both pools)
</td>
<td style="text-align:center;">
(kg N ha⁻¹)⁻¹ y⁻¹
</td>
<td style="text-align:right;">
0.0057
</td>
</tr>
<tr>
<td style="text-align:left;">
a₂
</td>
<td style="text-align:left;">
Throughfall and exudates: V → A
</td>
<td style="text-align:center;">
y⁻¹
</td>
<td style="text-align:right;">
0.0140
</td>
</tr>
<tr>
<td style="text-align:left;">
a₃
</td>
<td style="text-align:left;">
Litterfall: V → B
</td>
<td style="text-align:center;">
y⁻¹
</td>
<td style="text-align:right;">
0.0126
</td>
</tr>
<tr>
<td style="text-align:left;">
a₄
</td>
<td style="text-align:left;">
Net mineralization: B → A
</td>
<td style="text-align:center;">
y⁻¹
</td>
<td style="text-align:right;">
0.0149
</td>
</tr>
<tr>
<td style="text-align:left;">
a₅
</td>
<td style="text-align:left;">
Stream export from A
</td>
<td style="text-align:center;">
y⁻¹
</td>
<td style="text-align:right;">
0.1620
</td>
</tr>
<tr>
<td style="text-align:left;">
a₆
</td>
<td style="text-align:left;">
Stream export from B
</td>
<td style="text-align:center;">
y⁻¹
</td>
<td style="text-align:right;">
0.000021
</td>
</tr>
</tbody>
</table>
<p><strong>Note on measurement uncertainty:</strong> These parameters are derived from field measurements that have their own uncertainties. In a sensitivity analysis (Chapter <a href="#Model-Sensitivity"><strong>??</strong></a>), we would explore how uncertainty in these estimates affects model predictions. For now, we treat them as our best estimates.</p>
</div>
</div>
<div id="mathematical-solution" class="section level2 hasAnchor" number="5.12">
<h2><span class="header-section-number">5.12</span> Mathematical Solution<a href="N.html#mathematical-solution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <em>mathematical solution</em> is the process of making predictions using our model and our parameters. We <em>solve</em> the model. With simple models, we can sometimes find analytical solutions (like we did for steady states in Chapter <a href="first-order-compartments.html#first-order-compartments">3</a>). For most ecosystem models, we have to solve the models numerically using <em>numerical integration</em> - this is what computers excel at.</p>
<p>Here we write an R function that contains our system of differential equations. This will allow R’s <code>ode()</code> function from the <code>deSolve</code> package to integrate change through time.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="N.html#cb24-1" tabindex="-1"></a><span class="fu">library</span>(deSolve)</span>
<span id="cb24-2"><a href="N.html#cb24-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb24-3"><a href="N.html#cb24-3" tabindex="-1"></a></span>
<span id="cb24-4"><a href="N.html#cb24-4" tabindex="-1"></a>bormann1 <span class="ot">&lt;-</span> <span class="cf">function</span>(t, y, p) {</span>
<span id="cb24-5"><a href="N.html#cb24-5" tabindex="-1"></a>  <span class="co"># Arguments:</span></span>
<span id="cb24-6"><a href="N.html#cb24-6" tabindex="-1"></a>  <span class="co">#   t = time (used by ode() even though not explicitly in our equations)</span></span>
<span id="cb24-7"><a href="N.html#cb24-7" tabindex="-1"></a>  <span class="co">#   y = vector of state variables (V, A, B)</span></span>
<span id="cb24-8"><a href="N.html#cb24-8" tabindex="-1"></a>  <span class="co">#   p = vector of parameters</span></span>
<span id="cb24-9"><a href="N.html#cb24-9" tabindex="-1"></a>  </span>
<span id="cb24-10"><a href="N.html#cb24-10" tabindex="-1"></a>  <span class="co"># We use as.list() to make both state variables and parameters </span></span>
<span id="cb24-11"><a href="N.html#cb24-11" tabindex="-1"></a>  <span class="co"># directly accessible by name</span></span>
<span id="cb24-12"><a href="N.html#cb24-12" tabindex="-1"></a>  <span class="fu">with</span>( <span class="fu">as.list</span>( <span class="fu">c</span>(y, p) ), {</span>
<span id="cb24-13"><a href="N.html#cb24-13" tabindex="-1"></a>    </span>
<span id="cb24-14"><a href="N.html#cb24-14" tabindex="-1"></a>    <span class="co"># The three balance equations</span></span>
<span id="cb24-15"><a href="N.html#cb24-15" tabindex="-1"></a>    <span class="co"># Notice: we use subtraction for losses (following our sign convention)</span></span>
<span id="cb24-16"><a href="N.html#cb24-16" tabindex="-1"></a>    dV.dt <span class="ot">&lt;-</span> a1 <span class="sc">*</span> A <span class="sc">*</span> V <span class="sc">-</span> a2 <span class="sc">*</span> V <span class="sc">-</span> a3 <span class="sc">*</span> V</span>
<span id="cb24-17"><a href="N.html#cb24-17" tabindex="-1"></a>    dA.dt <span class="ot">&lt;-</span> i1 <span class="sc">+</span> a2 <span class="sc">*</span> V <span class="sc">+</span> a4 <span class="sc">*</span> B <span class="sc">-</span> a1 <span class="sc">*</span> A <span class="sc">*</span> V <span class="sc">-</span> a5 <span class="sc">*</span> A </span>
<span id="cb24-18"><a href="N.html#cb24-18" tabindex="-1"></a>    dB.dt <span class="ot">&lt;-</span> i2 <span class="sc">+</span> a3 <span class="sc">*</span> V <span class="sc">-</span> a4 <span class="sc">*</span> B <span class="sc">-</span> a6 <span class="sc">*</span> B </span>
<span id="cb24-19"><a href="N.html#cb24-19" tabindex="-1"></a>    </span>
<span id="cb24-20"><a href="N.html#cb24-20" tabindex="-1"></a>    <span class="co"># Return a LIST with two elements:</span></span>
<span id="cb24-21"><a href="N.html#cb24-21" tabindex="-1"></a>    <span class="co"># 1. Vector of rates (MUST be in same order as state variables)</span></span>
<span id="cb24-22"><a href="N.html#cb24-22" tabindex="-1"></a>    <span class="co"># 2. Additional outputs we want to track (total N in system)</span></span>
<span id="cb24-23"><a href="N.html#cb24-23" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">list</span>( </span>
<span id="cb24-24"><a href="N.html#cb24-24" tabindex="-1"></a>      <span class="fu">c</span>(dV.dt, dA.dt, dB.dt),     <span class="co"># rates for V, A, B</span></span>
<span id="cb24-25"><a href="N.html#cb24-25" tabindex="-1"></a>      <span class="at">total =</span> V <span class="sc">+</span> A <span class="sc">+</span> B            <span class="co"># total N for checking mass balance</span></span>
<span id="cb24-26"><a href="N.html#cb24-26" tabindex="-1"></a>    ))</span>
<span id="cb24-27"><a href="N.html#cb24-27" tabindex="-1"></a>  })</span>
<span id="cb24-28"><a href="N.html#cb24-28" tabindex="-1"></a>}</span></code></pre></div>
<p><strong>Understanding this function:</strong></p>
<ul>
<li>The function takes three arguments that <code>ode()</code> will provide</li>
<li>We use <code>with(as.list(...))</code> so we can refer to variables by name (like <code>V</code>, <code>a1</code>) instead of indexing (like <code>y[1]</code>, <code>p[3]</code>)</li>
<li>Each equation matches our mathematical model, using - for losses and + for gains</li>
<li>We return both the rates of change AND the total N (useful for verification)</li>
</ul>
<p>Now we set up the simulation:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="N.html#cb25-1" tabindex="-1"></a><span class="co"># Initial state: pool sizes from Bormann et al. (1977)</span></span>
<span id="cb25-2"><a href="N.html#cb25-2" tabindex="-1"></a>initial.state <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">V =</span> <span class="dv">532</span>, <span class="at">A =</span> <span class="dv">26</span>, <span class="at">B =</span> <span class="dv">4700</span>)</span>
<span id="cb25-3"><a href="N.html#cb25-3" tabindex="-1"></a></span>
<span id="cb25-4"><a href="N.html#cb25-4" tabindex="-1"></a><span class="co"># Time points: simulate for 20 years</span></span>
<span id="cb25-5"><a href="N.html#cb25-5" tabindex="-1"></a>time <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">20</span></span>
<span id="cb25-6"><a href="N.html#cb25-6" tabindex="-1"></a></span>
<span id="cb25-7"><a href="N.html#cb25-7" tabindex="-1"></a><span class="co"># Solve the system</span></span>
<span id="cb25-8"><a href="N.html#cb25-8" tabindex="-1"></a>out <span class="ot">&lt;-</span> <span class="fu">ode</span>(<span class="at">y =</span> initial.state, <span class="at">times =</span> time, <span class="at">func =</span> bormann1, <span class="at">parms =</span> params)</span>
<span id="cb25-9"><a href="N.html#cb25-9" tabindex="-1"></a></span>
<span id="cb25-10"><a href="N.html#cb25-10" tabindex="-1"></a><span class="co"># Display first 6 time points</span></span>
<span id="cb25-11"><a href="N.html#cb25-11" tabindex="-1"></a><span class="fu">head</span>(out)</span></code></pre></div>
<pre><code>##      time        V        A        B    total
## [1,]    0 532.0000 26.00000 4700.000 5258.000
## [2,]    1 536.9206 25.96500 4711.487 5274.373
## [3,]    2 541.5310 25.82774 4723.405 5290.764
## [4,]    3 545.7697 25.70512 4735.701 5307.176
## [5,]    4 549.6810 25.59949 4748.326 5323.606
## [6,]    5 553.3077 25.50854 4761.236 5340.052</code></pre>
<p><strong>What’s happening here:</strong></p>
<ul>
<li><code>ode()</code> starts at year 0 with our initial state</li>
<li>At each time step, it calculates the rates using <code>bormann1()</code></li>
<li>It uses sophisticated numerical methods to integrate forward in time</li>
<li>It returns a matrix with time in column 1, state variables in columns 2-4, and our custom output (total) in column 5</li>
</ul>
<p>Let’s visualize these dynamics:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="N.html#cb27-1" tabindex="-1"></a><span class="co"># Convert to long format for ggplot</span></span>
<span id="cb27-2"><a href="N.html#cb27-2" tabindex="-1"></a>outL <span class="ot">&lt;-</span> out <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="N.html#cb27-3" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb27-4"><a href="N.html#cb27-4" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>time, <span class="at">names_to =</span> <span class="st">&quot;State.var&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;kg.N&quot;</span>)</span>
<span id="cb27-5"><a href="N.html#cb27-5" tabindex="-1"></a></span>
<span id="cb27-6"><a href="N.html#cb27-6" tabindex="-1"></a><span class="co"># Create the plot</span></span>
<span id="cb27-7"><a href="N.html#cb27-7" tabindex="-1"></a><span class="fu">ggplot</span>(outL, <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> kg.N)) <span class="sc">+</span></span>
<span id="cb27-8"><a href="N.html#cb27-8" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb27-9"><a href="N.html#cb27-9" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>State.var, <span class="at">scales =</span> <span class="st">&quot;free_y&quot;</span>) <span class="sc">+</span></span>
<span id="cb27-10"><a href="N.html#cb27-10" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Time (years)&quot;</span>, </span>
<span id="cb27-11"><a href="N.html#cb27-11" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Nitrogen (kg N/ha)&quot;</span>,</span>
<span id="cb27-12"><a href="N.html#cb27-12" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Hubbard Brook N Budget Dynamics&quot;</span>) <span class="sc">+</span></span>
<span id="cb27-13"><a href="N.html#cb27-13" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-17"></span>
<img src="figs/unnamed-chunk-17-1.png" alt="Dynamics of a simple N budget model based on Bormann et al. (1977). Each panel shows one compartment over 20 years." width="75%" />
<p class="caption">
Figure 5.3: Dynamics of a simple N budget model based on Bormann et al. (1977). Each panel shows one compartment over 20 years.
</p>
</div>
</div>
<div id="interpreting-the-results" class="section level2 hasAnchor" number="5.13">
<h2><span class="header-section-number">5.13</span> Interpreting the Results<a href="N.html#interpreting-the-results" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>What do these trajectories tell us biologically?</strong></p>
<p><strong>1. Vegetation (V):</strong> Increases steadily over 20 years from 532 to about 680 kg N ha⁻¹.</p>
<p><em>Why?</em> The uptake term (a₁ × A × V) exceeds the loss terms (a₂ × V + a₃ × V) when V is at these levels. The forest is actively regrowing - this is an <em>aggrading</em> system accumulating biomass after disturbance.</p>
<p><em>Notice:</em> The rate of increase is slowing slightly - the curve is bending. This happens because as V grows, losses increase proportionally (more biomass → more litter), while uptake is limited by the declining available pool.</p>
<p><strong>2. Available pool (A):</strong> Declines from 26 to about 18 kg N ha⁻¹.</p>
<p><em>Why?</em> Vegetation is taking up more N than is being supplied by inputs (precipitation, mineralization). This makes ecological sense - an aggrading forest draws down the readily available nutrients. Plants are “mining” the available pool faster than it’s being replenished.</p>
<p><em>This creates a constraint:</em> As A declines, the uptake rate (a₁ × A × V) will eventually slow even if V keeps growing.</p>
<p><strong>3. Bound pool (B):</strong> Increases from 4,700 to about 4,950 kg N ha⁻¹.</p>
<p><em>Why?</em> Litter inputs (a₃ × V) exceed mineralization losses (a₄ × B) as the forest grows. The forest is storing carbon and nutrients in organic matter. This is typical of forest development - dead organic matter accumulates.</p>
<p><strong>4. Total system N:</strong> Increases from 5,258 to about 5,648 kg N ha⁻¹.</p>
<p><em>Why?</em> Inputs (I₁ + I₂ = 20.7 kg N ha⁻¹ y⁻¹) exceed exports (which depend on pools and are currently small). The system is a net nitrogen sink.</p>
<div id="the-key-problem" class="section level3 hasAnchor" number="5.13.1">
<h3><span class="header-section-number">5.13.1</span> The Key Problem<a href="N.html#the-key-problem" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>In this simple model, V would keep growing indefinitely.</strong> If you ran the simulation for 100 years, vegetation would continue accumulating nitrogen without bound.</p>
<p><strong>That’s biologically unrealistic.</strong> Real forests reach maximum biomass limited by:
- Light competition (trees shade each other)
- Space constraints (finite area for roots and crowns)
- Water and nutrient limitations
- Disturbance (windthrow, pathogens, etc.)</p>
<p>This motivates our next refinement: <strong>adding self-limitation</strong> to represent biological carrying capacity.</p>
</div>
<div id="mass-balance-check" class="section level3 hasAnchor" number="5.13.2">
<h3><span class="header-section-number">5.13.2</span> Mass Balance Check<a href="N.html#mass-balance-check" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s verify our model conserves mass correctly:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="N.html#cb28-1" tabindex="-1"></a><span class="co"># Calculate total system inputs and outputs at initial conditions</span></span>
<span id="cb28-2"><a href="N.html#cb28-2" tabindex="-1"></a>inputs <span class="ot">&lt;-</span> params[<span class="st">&quot;i1&quot;</span>] <span class="sc">+</span> params[<span class="st">&quot;i2&quot;</span>]</span>
<span id="cb28-3"><a href="N.html#cb28-3" tabindex="-1"></a>outputs_initial <span class="ot">&lt;-</span> params[<span class="st">&quot;a5&quot;</span>] <span class="sc">*</span> initial.state[<span class="st">&quot;A&quot;</span>] <span class="sc">+</span> params[<span class="st">&quot;a6&quot;</span>] <span class="sc">*</span> initial.state[<span class="st">&quot;B&quot;</span>]</span>
<span id="cb28-4"><a href="N.html#cb28-4" tabindex="-1"></a></span>
<span id="cb28-5"><a href="N.html#cb28-5" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Total inputs:&quot;</span>, inputs, <span class="st">&quot;kg N/ha/y</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Total inputs: 20.7 kg N/ha/y</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="N.html#cb30-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Initial outputs:&quot;</span>, outputs_initial, <span class="st">&quot;kg N/ha/y</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Initial outputs: 4.325493 kg N/ha/y</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="N.html#cb32-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Net accumulation rate:&quot;</span>, inputs <span class="sc">-</span> outputs_initial, <span class="st">&quot;kg N/ha/y</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## Net accumulation rate: 16.37451 kg N/ha/y</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="N.html#cb34-1" tabindex="-1"></a><span class="co"># Check that total change matches inputs - outputs</span></span>
<span id="cb34-2"><a href="N.html#cb34-2" tabindex="-1"></a><span class="co"># This is approximate because pools are changing</span></span>
<span id="cb34-3"><a href="N.html#cb34-3" tabindex="-1"></a>total_change <span class="ot">&lt;-</span> out[<span class="fu">nrow</span>(out), <span class="st">&quot;total&quot;</span>] <span class="sc">-</span> out[<span class="dv">1</span>, <span class="st">&quot;total&quot;</span>]</span>
<span id="cb34-4"><a href="N.html#cb34-4" tabindex="-1"></a>time_elapsed <span class="ot">&lt;-</span> <span class="fu">max</span>(time) <span class="sc">-</span> <span class="fu">min</span>(time)</span>
<span id="cb34-5"><a href="N.html#cb34-5" tabindex="-1"></a>avg_accumulation <span class="ot">&lt;-</span> total_change <span class="sc">/</span> time_elapsed</span>
<span id="cb34-6"><a href="N.html#cb34-6" tabindex="-1"></a></span>
<span id="cb34-7"><a href="N.html#cb34-7" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;</span><span class="sc">\n</span><span class="st">Predicted avg accumulation from model:&quot;</span>, <span class="fu">round</span>(avg_accumulation, <span class="dv">2</span>), <span class="st">&quot;kg N/ha/y</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Predicted avg accumulation from model: 16.48 kg N/ha/y</code></pre>
<p>The model’s accumulation rate is slightly less than inputs minus initial outputs because as pools change, export rates also change. This is correct behavior!</p>
</div>
</div>
<div id="exercise-add-self-limitation" class="section level2 hasAnchor" number="5.14">
<h2><span class="header-section-number">5.14</span> Exercise: Add Self-Limitation<a href="N.html#exercise-add-self-limitation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>The biological reality:</strong> As forests mature, growth slows even if nutrients remain available. Trees compete for light, space becomes limiting, and the ecosystem approaches a maximum biomass it can support - a <em>carrying capacity</em>.</p>
<p>This is a common pattern in ecology: populations and biomass pools show <strong>density-dependent growth</strong> - growth rate declines as density increases.</p>
<div id="your-task" class="section level3 hasAnchor" number="5.14.1">
<h3><span class="header-section-number">5.14.1</span> Your Task<a href="N.html#your-task" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Work through these steps before looking at the solution:</p>
<p><strong>1. Conceptual step:</strong></p>
<p>Where in the model should self-limitation appear? Think about which processes would slow down as vegetation approaches carrying capacity.</p>
<ul>
<li>Does precipitation become self-limiting? (No - rain falls regardless of forest biomass)</li>
<li>Does litterfall become self-limiting? (No - more vegetation → more litter)</li>
<li>Does plant growth become self-limiting? (Yes! This is the process to modify)</li>
</ul>
<p>Write out the modified balance equation for dV/dt in words before you write the math.</p>
<p><strong>2. Mathematical step:</strong></p>
<p>The standard form for self-limitation is:</p>
<p><span class="math display">\[\text{growth rate} \times \left(1 - \frac{V}{K}\right)\]</span></p>
<p>where K is carrying capacity. Think about what this multiplier does:
- When V = 0: multiplier = (1 - 0/K) = 1 (no limitation, full growth)
- When V = K/2: multiplier = (1 - 0.5) = 0.5 (half of maximum growth)
- When V = K: multiplier = (1 - K/K) = 0 (no growth, at carrying capacity)</p>
<p>In our current model, the net growth rate of vegetation is:</p>
<p><span class="math display">\[\frac{dV}{dt} = a_1 A V - a_2 V - a_3 V = (a_1 A - a_2 - a_3)V\]</span></p>
<p>Where should the self-limitation term go? Should it affect:
- Just uptake (a₁ × A × V)?
- Just net growth (the whole expression)?
- Individual loss terms?</p>
<p><strong>Hint:</strong> Biologically, self-limitation affects the <em>net growth rate</em>, not individual processes. Trees don’t stop dropping litter when crowded - they stop growing new tissue.</p>
<p><strong>3. Parameterization:</strong></p>
<p>We don’t have direct measurements of K from the Bormann data. We need to make an educated guess:</p>
<ul>
<li>The forest in 1977 had V = 532 kg N ha⁻¹</li>
<li>This was a young, aggrading forest</li>
<li>Mature northern hardwood forests might have 2-3× more biomass</li>
</ul>
<p>Based on this reasoning, what’s a reasonable estimate for K? Try K = 600 as a starting point (only slightly higher than current), but think about what would happen with K = 800 or K = 1000.</p>
<p><strong>4. Implementation:</strong></p>
<p>Modify the <code>bormann1</code> function to create <code>bormann2</code>. The change is small - just one multiplication in the dV.dt equation.</p>
<p><strong>5. Simulation and interpretation:</strong></p>
<ul>
<li>Run the model for 200 years (longer than before to see if it reaches equilibrium)</li>
<li>Plot all three compartments</li>
<li>Answer these questions:
<ul>
<li>Do all three pools approach equilibrium?</li>
<li>What are the equilibrium values?</li>
<li>How long does it take to get close to equilibrium?</li>
<li>What happens to the available pool as vegetation approaches K?</li>
</ul></li>
</ul>
</div>
<div id="work-on-this-before-looking-at-the-solution" class="section level3 hasAnchor" number="5.14.2">
<h3><span class="header-section-number">5.14.2</span> Work on This Before Looking at the Solution!<a href="N.html#work-on-this-before-looking-at-the-solution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Try to implement this yourself. Struggle is part of learning. The solution is hidden below.</p>
<details>
<summary>
<strong>Click here for solution after attempting the exercise</strong>
</summary>
</div>
<div id="solution-self-limited-model" class="section level3 hasAnchor" number="5.14.3">
<h3><span class="header-section-number">5.14.3</span> Solution: Self-Limited Model<a href="N.html#solution-self-limited-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Modified balance equation:</strong></p>
<p><span class="math display">\[\frac{dV}{dt} = (a_1 A - a_2 - a_3)V\left(1 - \frac{V}{K}\right)\]</span></p>
<p>The self-limitation term multiplies the entire net growth rate. When V is small, (1 - V/K) ≈ 1 and growth proceeds normally. As V approaches K, (1 - V/K) → 0 and growth slows to zero.</p>
<p><strong>Implementation in R:</strong></p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="N.html#cb36-1" tabindex="-1"></a>bormann2 <span class="ot">&lt;-</span> <span class="cf">function</span>(t, y, p) {</span>
<span id="cb36-2"><a href="N.html#cb36-2" tabindex="-1"></a>  <span class="co"># Same structure as bormann1, but with self-limitation in vegetation</span></span>
<span id="cb36-3"><a href="N.html#cb36-3" tabindex="-1"></a>  <span class="fu">with</span>( <span class="fu">as.list</span>( <span class="fu">c</span>(y, p) ), {</span>
<span id="cb36-4"><a href="N.html#cb36-4" tabindex="-1"></a>    </span>
<span id="cb36-5"><a href="N.html#cb36-5" tabindex="-1"></a>    <span class="co"># Modified vegetation equation with carrying capacity</span></span>
<span id="cb36-6"><a href="N.html#cb36-6" tabindex="-1"></a>    dV.dt <span class="ot">&lt;-</span> (a1 <span class="sc">*</span> A <span class="sc">-</span> a2 <span class="sc">-</span> a3) <span class="sc">*</span> V <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> V<span class="sc">/</span>K)</span>
<span id="cb36-7"><a href="N.html#cb36-7" tabindex="-1"></a>    </span>
<span id="cb36-8"><a href="N.html#cb36-8" tabindex="-1"></a>    <span class="co"># A and B equations unchanged</span></span>
<span id="cb36-9"><a href="N.html#cb36-9" tabindex="-1"></a>    dA.dt <span class="ot">&lt;-</span> i1 <span class="sc">+</span> a2 <span class="sc">*</span> V <span class="sc">+</span> a4 <span class="sc">*</span> B <span class="sc">-</span> a1 <span class="sc">*</span> A <span class="sc">*</span> V <span class="sc">-</span> a5 <span class="sc">*</span> A </span>
<span id="cb36-10"><a href="N.html#cb36-10" tabindex="-1"></a>    dB.dt <span class="ot">&lt;-</span> i2 <span class="sc">+</span> a3 <span class="sc">*</span> V <span class="sc">-</span> a4 <span class="sc">*</span> B <span class="sc">-</span> a6 <span class="sc">*</span> B </span>
<span id="cb36-11"><a href="N.html#cb36-11" tabindex="-1"></a>    </span>
<span id="cb36-12"><a href="N.html#cb36-12" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">list</span>( </span>
<span id="cb36-13"><a href="N.html#cb36-13" tabindex="-1"></a>      <span class="fu">c</span>(dV.dt, dA.dt, dB.dt),</span>
<span id="cb36-14"><a href="N.html#cb36-14" tabindex="-1"></a>      <span class="at">total =</span> V <span class="sc">+</span> A <span class="sc">+</span> B </span>
<span id="cb36-15"><a href="N.html#cb36-15" tabindex="-1"></a>    ))</span>
<span id="cb36-16"><a href="N.html#cb36-16" tabindex="-1"></a>  })</span>
<span id="cb36-17"><a href="N.html#cb36-17" tabindex="-1"></a>}</span></code></pre></div>
<p><strong>Add carrying capacity to parameters:</strong></p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="N.html#cb37-1" tabindex="-1"></a>params[<span class="st">&quot;K&quot;</span>] <span class="ot">&lt;-</span> <span class="dv">600</span>  <span class="co"># carrying capacity in kg N/ha</span></span></code></pre></div>
<p><strong>Run simulation for 200 years:</strong></p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="N.html#cb38-1" tabindex="-1"></a>initial.state <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">V =</span> <span class="dv">532</span>, <span class="at">A =</span> <span class="dv">26</span>, <span class="at">B =</span> <span class="dv">4700</span>)</span>
<span id="cb38-2"><a href="N.html#cb38-2" tabindex="-1"></a>time <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">200</span></span>
<span id="cb38-3"><a href="N.html#cb38-3" tabindex="-1"></a></span>
<span id="cb38-4"><a href="N.html#cb38-4" tabindex="-1"></a>out2 <span class="ot">&lt;-</span> <span class="fu">ode</span>(<span class="at">y =</span> initial.state, <span class="at">times =</span> time, <span class="at">func =</span> bormann2, <span class="at">parms =</span> params)</span></code></pre></div>
<p><strong>Visualize the dynamics:</strong></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="N.html#cb39-1" tabindex="-1"></a>outL2 <span class="ot">&lt;-</span> out2 <span class="sc">%&gt;%</span> </span>
<span id="cb39-2"><a href="N.html#cb39-2" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="N.html#cb39-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>time, <span class="at">names_to =</span> <span class="st">&quot;State.var&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;kg.N&quot;</span>)</span>
<span id="cb39-4"><a href="N.html#cb39-4" tabindex="-1"></a></span>
<span id="cb39-5"><a href="N.html#cb39-5" tabindex="-1"></a><span class="fu">ggplot</span>(outL2, <span class="fu">aes</span>(time, kg.N)) <span class="sc">+</span> </span>
<span id="cb39-6"><a href="N.html#cb39-6" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;darkgreen&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb39-7"><a href="N.html#cb39-7" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>State.var, <span class="at">scales =</span> <span class="st">&quot;free_y&quot;</span>) <span class="sc">+</span></span>
<span id="cb39-8"><a href="N.html#cb39-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Time (years)&quot;</span>, </span>
<span id="cb39-9"><a href="N.html#cb39-9" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Nitrogen (kg N/ha)&quot;</span>,</span>
<span id="cb39-10"><a href="N.html#cb39-10" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Self-Limited N Budget (K = 600)&quot;</span>) <span class="sc">+</span></span>
<span id="cb39-11"><a href="N.html#cb39-11" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-21"></span>
<img src="figs/unnamed-chunk-21-1.png" alt="Dynamics of N budget with density-dependent vegetation growth. The system approaches equilibrium over ~150 years." width="75%" />
<p class="caption">
Figure 5.4: Dynamics of N budget with density-dependent vegetation growth. The system approaches equilibrium over ~150 years.
</p>
</div>
<p><strong>Interpretation:</strong></p>
<ol style="list-style-type: decimal">
<li><p><strong>Vegetation (V):</strong> Approaches K = 600 asymptotically. Growth is rapid initially, then slows as it approaches carrying capacity. After ~150 years, it’s essentially at equilibrium around 598 kg N ha⁻¹.</p></li>
<li><p><strong>Available pool (A):</strong> Initially declines (same as before), but then slowly recovers as vegetation growth slows. At equilibrium, it stabilizes around 12-13 kg N ha⁻¹ - lower than the initial 26, but no longer being depleted.</p></li>
<li><p><strong>Bound pool (B):</strong> Continues accumulating organic matter, but the rate slows as litter inputs slow (since V stops growing). Approaches equilibrium around 5,850 kg N ha⁻¹.</p></li>
<li><p><strong>Total system:</strong> Continues accumulating because inputs &gt; outputs, but the rate slows. The system is approaching a true steady state where inputs = outputs.</p></li>
</ol>
<p><strong>What causes equilibrium?</strong></p>
<p>At equilibrium, dV/dt = 0, which requires either:
- V = 0 (trivial solution - no forest), or<br />
- V = K (at carrying capacity), or
- a₁ × A = a₂ + a₃ (uptake rate equals loss rate)</p>
<p>In our model, the system approaches the third condition: V grows until it has drawn down A to a level where uptake exactly balances losses. The self-limitation ensures V can’t overshoot and oscillate.</p>
</details>
</div>
<div id="questions-to-ponder" class="section level3 hasAnchor" number="5.14.4">
<h3><span class="header-section-number">5.14.4</span> Questions to Ponder<a href="N.html#questions-to-ponder" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>What would happen if K = 800 instead of 600? Try it!</li>
<li>At equilibrium, what determines the value of A? (Hint: set dV/dt = 0 and solve)</li>
<li>Why does B keep increasing even after V stops growing?</li>
<li>How would clearcutting affect this system? (Set V = 50 and re-run)</li>
</ol>
</div>
</div>
<div id="saving-your-model-function" class="section level2 hasAnchor" number="5.15">
<h2><span class="header-section-number">5.15</span> Saving Your Model Function<a href="N.html#saving-your-model-function" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Important for future work:</strong> Make a new R script containing just the <code>bormann2</code> function. This creates a reusable module:</p>
<ol style="list-style-type: decimal">
<li>Copy the complete <code>bormann2</code> function definition</li>
<li>Paste it into a new R script</li>
<li>Save as <strong>bormann2.R</strong> in your working directory</li>
</ol>
<p>We’ll use this function in Chapter <a href="#Model-Sensitivity"><strong>??</strong></a> for sensitivity analysis. Having it as a separate file makes it easy to <code>source()</code> into other scripts.</p>
</div>
<div id="common-issues-and-troubleshooting" class="section level2 hasAnchor" number="5.16">
<h2><span class="header-section-number">5.16</span> Common Issues and Troubleshooting<a href="N.html#common-issues-and-troubleshooting" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Here are solutions to problems students often encounter:</p>
<div id="error-could-not-find-function-ode" class="section level3 hasAnchor" number="5.16.1">
<h3><span class="header-section-number">5.16.1</span> Error: “could not find function ‘ode’”<a href="N.html#error-could-not-find-function-ode" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Cause:</strong> The deSolve package isn’t loaded.</p>
<p><strong>Solution:</strong></p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="N.html#cb40-1" tabindex="-1"></a><span class="fu">library</span>(deSolve)</span></code></pre></div>
</div>
<div id="warning-lsoda-at-t-too-much-accuracy-requested" class="section level3 hasAnchor" number="5.16.2">
<h3><span class="header-section-number">5.16.2</span> Warning: “lsoda– at t…, too much accuracy requested”<a href="N.html#warning-lsoda-at-t-too-much-accuracy-requested" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Cause:</strong> Usually indicates a parameter error making the system numerically unstable.</p>
<p><strong>Troubleshooting steps:</strong>
1. Check that all parameters are positive (we took absolute values)
2. Verify units are consistent across all terms
3. Check for typos in the differential equation function
4. Make sure you’re subtracting losses, not adding them</p>
</div>
<div id="graph-shows-exponential-explosion-or-negative-values" class="section level3 hasAnchor" number="5.16.3">
<h3><span class="header-section-number">5.16.3</span> Graph shows exponential explosion or negative values<a href="N.html#graph-shows-exponential-explosion-or-negative-values" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Likely causes:</strong>
- Sign error: adding a loss instead of subtracting, or vice versa
- Missing absolute value: negative parameter causing growth instead of decay
- Wrong units: parameter too large by a factor of 10, 100, etc.</p>
<p><strong>Debug approach:</strong></p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="N.html#cb41-1" tabindex="-1"></a><span class="co"># Check parameter values</span></span>
<span id="cb41-2"><a href="N.html#cb41-2" tabindex="-1"></a><span class="fu">print</span>(params)</span>
<span id="cb41-3"><a href="N.html#cb41-3" tabindex="-1"></a></span>
<span id="cb41-4"><a href="N.html#cb41-4" tabindex="-1"></a><span class="co"># Run for just 1 year to see initial behavior</span></span>
<span id="cb41-5"><a href="N.html#cb41-5" tabindex="-1"></a>time_short <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span></span>
<span id="cb41-6"><a href="N.html#cb41-6" tabindex="-1"></a>out_test <span class="ot">&lt;-</span> <span class="fu">ode</span>(<span class="at">y =</span> initial.state, <span class="at">times =</span> time_short, </span>
<span id="cb41-7"><a href="N.html#cb41-7" tabindex="-1"></a>                <span class="at">func =</span> bormann2, <span class="at">parms =</span> params)</span>
<span id="cb41-8"><a href="N.html#cb41-8" tabindex="-1"></a><span class="fu">print</span>(out_test)</span>
<span id="cb41-9"><a href="N.html#cb41-9" tabindex="-1"></a></span>
<span id="cb41-10"><a href="N.html#cb41-10" tabindex="-1"></a><span class="co"># Calculate rates at initial conditions manually</span></span>
<span id="cb41-11"><a href="N.html#cb41-11" tabindex="-1"></a><span class="fu">with</span>(<span class="fu">as.list</span>(<span class="fu">c</span>(initial.state, params)), {</span>
<span id="cb41-12"><a href="N.html#cb41-12" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;dV/dt =&quot;</span>, a1<span class="sc">*</span>A<span class="sc">*</span>V <span class="sc">-</span> a2<span class="sc">*</span>V <span class="sc">-</span> a3<span class="sc">*</span>V))</span>
<span id="cb41-13"><a href="N.html#cb41-13" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;dA/dt =&quot;</span>, i1 <span class="sc">+</span> a2<span class="sc">*</span>V <span class="sc">+</span> a4<span class="sc">*</span>B <span class="sc">-</span> a1<span class="sc">*</span>A<span class="sc">*</span>V <span class="sc">-</span> a5<span class="sc">*</span>A))</span>
<span id="cb41-14"><a href="N.html#cb41-14" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;dB/dt =&quot;</span>, i2 <span class="sc">+</span> a3<span class="sc">*</span>V <span class="sc">-</span> a4<span class="sc">*</span>B <span class="sc">-</span> a6<span class="sc">*</span>B))</span>
<span id="cb41-15"><a href="N.html#cb41-15" tabindex="-1"></a>})</span></code></pre></div>
</div>
<div id="model-doesnt-reach-equilibrium" class="section level3 hasAnchor" number="5.16.4">
<h3><span class="header-section-number">5.16.4</span> Model doesn’t reach equilibrium<a href="N.html#model-doesnt-reach-equilibrium" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>This might be correct!</strong> Not all systems reach equilibrium. Check:
- Are inputs constant or do they balance outputs?
- Is there a steady drain without compensating input?
- Did you run long enough? Try 500 or 1000 years</p>
</div>
<div id="pools-go-negative" class="section level3 hasAnchor" number="5.16.5">
<h3><span class="header-section-number">5.16.5</span> Pools go negative<a href="N.html#pools-go-negative" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>This is always wrong</strong> - you can’t have negative mass.</p>
<p><strong>Causes:</strong>
- Loss rate too high relative to pool size
- Wrong initial conditions
- Time step too large (rare with <code>ode()</code>, but possible)</p>
</div>
</div>
<div id="connections-to-previous-chapters" class="section level2 hasAnchor" number="5.17">
<h2><span class="header-section-number">5.17</span> Connections to Previous Chapters<a href="N.html#connections-to-previous-chapters" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s recap how this chapter builds on earlier material:</p>
<p><strong>From Chapter <a href="intro.html#intro">4</a>:</strong>
- We use the same balance equation framework: Change = Sources - Sinks
- We verify mass balance by summing all compartments
- We distinguish state variables (V, A, B) from parameters (a₁, a₂, etc.)</p>
<p><strong>From Chapter <a href="simple-budgets.html#simple-budgets">2</a>:</strong>
- We use constant (zero-order) inputs just like Example 1-4
- We see how constant inputs can lead to accumulation (Examples 1, 2) or depletion (Example 4)</p>
<p><strong>From Chapter <a href="first-order-compartments.html#first-order-compartments">3</a>:</strong>
- We use first-order loss kinetics: flux = k × Pool
- We calculate steady states by setting dX/dt = 0
- We understand residence time and turnover
- We see how coupling compartments creates interdependence</p>
<p><strong>New in this chapter:</strong>
- Combining zero-order and first-order processes in one model
- Using literature data to estimate parameters
- Distinguishing annual rates from instantaneous rates
- Adding density-dependence (self-limitation)
- Working with a real published ecosystem model</p>
</div>
<div id="summary-and-key-takeaways" class="section level2 hasAnchor" number="5.18">
<h2><span class="header-section-number">5.18</span> Summary and Key Takeaways<a href="N.html#summary-and-key-takeaways" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>What you’ve learned:</strong></p>
<ol style="list-style-type: decimal">
<li><p><strong>Real ecosystems combine multiple rate types</strong> - some fluxes are constant (precipitation), others depend on pool sizes (mineralization, uptake)</p></li>
<li><p><strong>Parameterization requires careful attention to:</strong></p>
<ul>
<li>Units (always check that equations balance dimensionally)</li>
<li>Signs (gains vs. losses)</li>
<li>Rate types (instantaneous vs. annual)</li>
</ul></li>
<li><p><strong>Model interpretation is biological</strong> - don’t just make graphs, explain what they mean ecologically</p></li>
<li><p><strong>Models iterate</strong> - we started simple (bormann1) and added realism (bormann2). This is normal!</p></li>
<li><p><strong>Mass balance is non-negotiable</strong> - if total system change ≠ inputs - outputs, you have an error</p></li>
<li><p><strong>Self-limitation is crucial</strong> for realistic long-term dynamics of biological populations and biomass</p></li>
</ol>
<p><strong>Next steps:</strong></p>
<p>In Chapter <a href="#Model-Sensitivity"><strong>??</strong></a>, we’ll explore:
- How uncertainty in parameters affects predictions<br />
- Which parameters matter most
- How to systematically explore parameter space
- Making robust predictions despite uncertainty</p>
<p>You now have a working ecosystem model based on real data. That’s a significant accomplishment!</p>
</div>
<div id="references" class="section level2 hasAnchor" number="5.19">
<h2><span class="header-section-number">5.19</span> References<a href="N.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Bormann, F.H., G.E. Likens, T.G. Siccama, R.S. Pierce, and J.S. Eaton. 1977. The export of nutrients and recovery of stable conditions following deforestation at Hubbard Brook. <em>Ecological Monographs</em> 47:255-277.</p>
<p>Soetaert, K. and P.M.J. Hermann. 2009. <em>A Practical Guide to Ecological Modelling.</em> Springer, Dordrecht.</p>

</div>
</div>
<h3> References<a href="references-1.html#references-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-bormann1977" class="csl-entry">
Bormann, F. H., G. E. Likens, and J. M. Melillo. 1977. <span>“Nitrogen Budget for a Aggrading Northern Hardwood Forest Ecosystem.”</span> <em>Science</em> 196 (4293): 981–83. <a href="https://doi.org/10.1126/science.196.4293.981">https://doi.org/10.1126/science.196.4293.981</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="lake-metabolism.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
